### ISSUE TITLE
Volume in different location than Pod

### ISSUE THREAD

**Issue by mcadam** [hetznercloud/csi-driver#10]
Hi, I am having an issue where the Volume seems to be created in one region and then the pod asking for it in a different region.
Here is the error:

```desc = failed to publish volume: server and volume must be in the same location```

I have a cluster with workers in different region, is this something the driver is not compatible with?

**Comment by thcyron** [comment]
In general, a volume and a server must be in the same location in order for the volume to be attached to the server. The CSI driver always creates volumes in the location where the controller is running, i.e. where the pods for the stateful set `hcloud-csi-controller` are deployed. So, unfortunately, the CSI driver doesn’t work well with multi-location clusters.

I need to dig more into the lifecycle of persistent volumes inside Kubernetes to understand if/how we can add support for multi-location clusters. I think the `PersistentVolumeClaim` somehow needs to be annotated with the location where to create the volume.

**Comment by apricote** [comment]
The CSI spec supports a `TopologyRequirement` for the `CreateVolumeRequest`, you can use this to specify the requested region for the Volume.

I do not know how the Kubernetes integration for this looks like.

https://github.com/container-storage-interface/spec/blob/v1.0.0/csi.proto#L251

**Comment by thcyron** [comment]
On the Kubernetes side, what’s needed here is a `StorageClass` with a volume binding mode of `WaitForFirstConsumer`:

https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode

What’s still unclear to me is how the CSI driver will know the node’s location when a new volume should be provisioned?

**Comment by ahilsend** [comment]
The aws-ebs-csi driver is topology aware, maybe this helps: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/760663ccad33c3906a4ddc41ead35fb353b627b8

**Comment by apricote** [comment]
The design proposal for the Kubernetes CSI integration includes further documentation on this: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md (`Ctrl+F` and search for `Topology`)

**Comment by deacix** [comment]
Hi everyone! What is the state? I have still the same problem with 1.1.4
