### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by andy812** [hetznercloud/csi-driver#101]
I tried to deploy csi-driver on k8s 1.16 and faced with errors.
My hcloud-csi-node pod (hcloud-csi-driver container) logs:
```
Loading...level=debug ts=2020-02-07T14:50:18.536494665Z msg="getting instance id from metadata service"
level=debug ts=2020-02-07T14:50:29.346095831Z msg="fetching server"
level=error ts=2020-02-07T14:50:39.382034529Z msg="failed to fetch server" err="Get https://api.hetzner.cloud/v1/servers/4494003: net/http: TLS handshake timeout"
```
i used docker image hetznercloud/hcloud-csi-driver:1.2.2.
How can i fix it?

**Comment by LKaemmerling** [comment]
We don't see an error on our side. This looks like there is something wrong with your network configuration.

**Comment by andy812** [comment]
Our network configuration is ok because i can call API (curl https://api.hetzner.cloud/v1/servers/4494003 with bearer token) from server, but not from container.

**Comment by LKaemmerling** [comment]
Then it looks like the container doesn’t have network access. This is a error in your cluster which is independent from the csi driver.

**Comment by identw** [comment]
Found a problem for myself, it looks like I allocated too few resources to the controller, because of this, the controller was executing requests for a very long time. The problem was not a network one.
