### ISSUE TITLE
Rancher Volume Change Capacity

### ISSUE THREAD

**Issue by excme** [hetznercloud/csi-driver#102]
Csi-driver Not fully compatible with Rancher. Plugin can`t change capacity of Persistent Volume.
![image](https://user-images.githubusercontent.com/13168074/74291259-59a09600-4d45-11ea-8e51-c2dfdb9b378a.png)

**csi-driver:** master
**rancher:** v2.3.5

**Comment by LKaemmerling** [comment]
We officially don't support rancher. As long as i know there is a specific plugin within rancher needed.
