### ISSUE TITLE
Upgrade instructions

### ISSUE THREAD

**Issue by hadifarnoud** [hetznercloud/csi-driver#105]
I use old driver that is depricated now on Rancher. it's creating problems for me and I need to upgrade.

just didn't find any instructions
<img width="1012" alt="Screen Shot 1398-12-15 at 19 22 46" src="https://user-images.githubusercontent.com/589808/75998867-b5aaa480-5f16-11ea-8e51-93c17227c86f.png">

**Comment by LKaemmerling** [comment]
I think you are on the wrong repository. You should ask this to https://github.com/mxschmitt/ui-driver-hetzner or https://github.com/JonasProgrammer/docker-machine-driver-hetzner
