### ISSUE TITLE
Is resizing volumes safe?

### ISSUE THREAD

**Issue by vitobotta** [hetznercloud/csi-driver#106]
Hi! I am planning on using Minio in my cluster for an app that might potentially collect lots of user updates over time, so I would like to start with small volumes and resize when needed later. Is this safe with the current version of the CSI driver? Unrelated question: to upgrade do I just change the version/tag of the image? Thanks!

**Comment by LKaemmerling** [comment]
Hey, 

we use the resizing feature ourselves for our test environment. It works really good and safe. Keep in mind that you can only increase the size of a volume.

For updating, we recommend applying the latest deployment file as a whole, because there might be some dependencies that were updated.

**Comment by vitobotta** [comment]
I applied the new YAML and verified that the csi driver is now 1.2.3. I also see that the volume expansion is set to true in the storage class. However when I edit a PVC I see this in the events of the pvc and the resizing doesn't happen even after restarting the pod

```
Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC
```

I think I am having the same problems as in https://github.com/hetznercloud/csi-driver/issues/96 which 1.2.3 should fix? Thanks
