### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by grigorov** [hetznercloud/csi-driver#108]
I can't find official helm chart. I will can create helm chart for this project.

**Comment by invidian** [comment]
I've created a helm chart for it, which also includes some fixes (#110), as well as `PodSecurityPolicy` for both deployments (though not very restrictive).

It's available from the following repository: `https://flexkube.github.io/charts/` under `hcloud-csi` name.

**Comment by grigorov** [comment]
Hi @invidian , can you upgrade your helm chart to v1.3.0 csi-driver?

**Comment by invidian** [comment]
@grigorov feel free to raise a PR/create an issue about it in https://github.com/flexkube/hcloud-csi-helm-chart. I'll do it when I get some free time.

**Comment by grigorov** [comment]
ok, after approve #116 , i create PR to your repository with changes.

**Comment by grigorov** [comment]
I create PR https://github.com/flexkube/hcloud-csi-helm-chart/pull/1  with version 1.3.1

**Comment by CuBiC3D** [comment]
Would also like to see an official Helm Chart using some best practices. Really annoying to patch secrets name with kustomize to match those from the hcloud-controller(also no Helm), would also like to set tolerations or HA options.

**Comment by invidian** [comment]
@CuBiC3D feel free to raise issues/PRs to https://github.com/flexkube/hcloud-csi-helm-chart with suggestions for improvements.

**Comment by CuBiC3D** [comment]
@invidian I'm always happy to help, but this would solve the problem only partially. It requires to maintain a chart and kinda "refit" values again on upstream updates. But the biggest problem here: This is an unofficial chart and repository that consumes a token with unlimited access to a project running the whole cluster. That should usually be against the company's policy.

**Comment by mohsinhijazee** [comment]
Don't think hertzner API has any roles and restrictions in place for their API or do they?

**Comment by CuBiC3D** [comment]
> Don't think hertzner API has any roles and restrictions in place for their API or do they?

Nope, the token is valid for the whole project without any restrictions.

**Comment by LKaemmerling** [comment]
We don't plan to provide a helm chart for our csi driver as you don't need to template that much to use the CSI driver

**Comment by MatthiasLohr** [comment]
Since I was creating a Helm Chart for hcloud-cloud-controller-manager anyways, I also decided to create a Helm Chart for the CSI driver on my own which offers some more documentation and configuration parameters: https://gitlab.com/MatthiasLohr/hcloud-csi-driver-helm-chart. Maybe this is of interest for someone. Disadvantage: I didn't include a PodSecurityPolicy (yet).
