### ISSUE TITLE
Will it work with Hashicorp Nomad?

### ISSUE THREAD

**Issue by pySilver** [hetznercloud/csi-driver#109]
Latest Nomad has CSI support for official kubernetes plugins, however HCloud is not listed at https://kubernetes-csi.github.io/docs/drivers.html

Will it work with Nomad?

See: https://www.hashicorp.com/blog/hashicorp-nomad-container-storage-interface-csi-beta/

**Comment by LKaemmerling** [comment]
As we follow the official spec, it should work even if we don't support or test the CSI on Nomad. You could try it and post your result to this issue, so maybe other users can find this.

**Comment by pySilver** [comment]
Great! Once I find out how they discover & load modules I'll be happy to test it.
