### ISSUE TITLE
Failed to resize pvc due to insufficient permissions in 1.2.3

### ISSUE THREAD

**Issue by jekakm** [hetznercloud/csi-driver#110]
Looks like you just forgot to make changes in deploy/kubernetes/hcloud-csi.yml that you made in hcloud-csi-master.yaml. (https://github.com/hetznercloud/csi-driver/commit/bb3f30bd16172cfb6d53dbf4b9943abd55dcaffa)
But in documentation used hcloud-csi.yml file and as result resizing won't working, if I update ClusterRole manually - looks like all works fine.

**Comment by spatialy** [comment]
Confirmed, same issue here

**Comment by invidian** [comment]
Created PR to fix it #111.
