### ISSUE TITLE
CSI attaches the PVC to a node which is not even a part of K8s Cluster

### ISSUE THREAD

**Issue by yousafsyed** [hetznercloud/csi-driver#131]
Kubernetes Version: v1.15.11
CSI is deployed via the following Command: 
` kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v1.1.5/deploy/kubernetes/hcloud-csi.yml`

I have CSI installed in my k8s cluster and its working without any error but, when I create a pod with a persistent volume claim CSI does create a PVC for that pod but it attaches the PVC in HCLOUD to a node which is not the same as pod and also that node is not even in the k8s cluster, which the most strange part.

**Comment by LKaemmerling** [comment]
Do you route the whole traffic over this specific node? The CSI needs a route to 169.254.169.254 (the metadataserver) on every server. (Which is the normal case when every server is directly connected with its public interface)

**Comment by yousafsyed** [comment]
@LKaemmerling  Yes thats the router in my case for outgoing traffic. but for incomming traffic I can access those nodes on internal IPS

**Comment by LKaemmerling** [comment]
And that is the problem here. The Metadata Server thinks the request comes from the router server and therefore respond with its ID. If you route the specific IP over every public interface of every node it will directly work :)

**Comment by LKaemmerling** [comment]
You can find more details in #104

**Comment by yousafsyed** [comment]
Now I understand better how CSI determines what server to attach the IP to, but since I want to use router when I go to the internet for our business use case how can I route the specific IP over every public interface and still use the router for outgoing connections?

Can you shed some light on this part? I really appreciate your help. Thanks in Advance

**Comment by LKaemmerling** [comment]
Yeah correct, just one route on every server which goes over the public interface (ens* or eth*) instead of over the router.

**Comment by yousafsyed** [comment]
Perfect, This worked for me what I have done is following

auto ens10
iface ens10 inet dhcp
        post-up ip route add default via 10.0.0.1 #Routes all the traffic via router
	post-up ip route add 169.254.169.254 dev eth0 #Routes the traffic via main interface just for the metadata server

**Comment by LKaemmerling** [comment]
Great that I works for you now :) I will pin this issue to the top so other users can easily find it.

**Comment by JWDobken** [comment]
sorry I need a slightly, step-by-step, detailed manual :|

kubernetes: 1.18.0
ubuntu: 18.04

**Comment by LKaemmerling** [comment]
@JWDobken you could use the latest master release, there it is no longer directly needed to use the metadataservice as this "master version" uses the node name for identification and falls back to the metadata service.

**Comment by JWDobken** [comment]
Thanks for your response @LKaemmerling, as I said my issue is more similar to #139 so I dropped my problem description there
