### ISSUE TITLE
PVC stays at FileSystemResizePending forever

### ISSUE THREAD

**Issue by Izvunzemen** [hetznercloud/csi-driver#136]
After I applied latest version of hcloud-csi.yml, I expect to have capability to extend volumes.

But actually only think that extend to the new size was PV itself, PVC stays at FileSystemResizePending and it says "_Waiting for user to (re-)start a pod to finish file system resize of volume on node._"  I tried to delete the volume and recreate it, and to make it part of deployment, scale it down to 0 and then 1 again, it didn't help.

In the StorageClass definition, i can see - allowVolumeExpansion: true 

How i tried to extend volume

**kubectl apply -f csi-test.yaml**

with content:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hcloud-volumes
---
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: nginx 
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume2
  volumes:
    - name: my-csi-volume2
      persistentVolumeClaim:
        claimName: csi-pvc
```

Then i changed storage from 20gb to 30gb, and apply the yaml again. Looks like volume in hetzner was increased to 30 gb, but not pvc:

**kubectl get pvc csi-pvc -o yaml**

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"csi-pvc","namespace":"csi-test"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"30Gi"}},"storageClassName":"hcloud-volumes"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi.hetzner.cloud
    volume.kubernetes.io/selected-node: k8s-node01
  creationTimestamp: "2020-07-24T06:08:49Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: csi-pvc
  namespace: csi-test
  resourceVersion: "146954043"
  selfLink: /api/v1/namespaces/csi-test/persistentvolumeclaims/csi-pvc
  uid: 2fed974f-6515-4e52-8997-0582536e9ade
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: hcloud-volumes
  volumeMode: Filesystem
  volumeName: pvc-2fed974f-6515-4e52-8997-0582536e9ade
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-07-24T06:09:34Z"
    message: Waiting for user to (re-)start a pod to finish file system resize of
      volume on node.
    status: "True"
    type: FileSystemResizePending
  phase: Bound
```

Then i tried to kill the pod and reapply the yaml file, as i mention, i also tried to make it depoyment, and scale down to 0, then scale back to 1 pod, but PVC is staying at same state.

**Comment by jekakm** [comment]
I think, developers will be need more details about your Kubernetes installation, because for example in my kubeadm install with version 1.17.8 volumes resizing works well.

**Comment by Izvunzemen** [comment]
Kubernetes Master and Nodes version - v1.15.1
Provisioned on Hetzner VM's with Ansible Kubespray.

Tell me if you need more detailed info about anything.

**Comment by LKaemmerling** [comment]
As listened in the error message you need to restart the pod where the volume will be used:
```
    message: Waiting for user to (re-)start a pod to finish file system resize of
      volume on node.
```

**Comment by Izvunzemen** [comment]
> As listened in the error message you need to restart the pod where the volume will be used:
> 
> ```
>     message: Waiting for user to (re-)start a pod to finish file system resize of
>       volume on node.
> ```

Yeah, i already tried to kill the pod and recreate it, also, to make it part of deployment and to scale down to 0 and 1 again.

**Comment by LKaemmerling** [comment]
Have a look at: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#csi-volume-expansion

I guess you k8s version (1.15.1) does not support it.

**Comment by jekakm** [comment]
https://kubernetes-csi.github.io/docs/volume-expansion.html
yeah, it's alpha feature in 1.15, you need manualy enable it (i not recomend it for production usage)

**Comment by Izvunzemen** [comment]
Thank you, guys.
