### ISSUE TITLE
Snapshot support

### ISSUE THREAD

**Issue by malikkirchner** [hetznercloud/csi-driver#140]
Hi,

I am very happy about the growing Hetzer support for Kubernets. Great work! We at xelonic use this csi-driver to provision our volumes in production. Snapshot support would be a great time saver for us.
* Use case 1) A volume claim is deleted with retainPolicy: Retain. It would be great to have automatic snapshot creation, that we can spin up a new volume claim from an earlier snapshot. That way the Hetzner volume would still be represented in k8s and would not dangle. 
* Use case 2) Backups for e.g. cluster migration, database "warm ups", ...

**Comment by grigorov** [comment]
+1

**Comment by grizzo-fsm** [comment]
+1

**Comment by grengojbo** [comment]
+1

**Comment by invidian** [comment]
not stale please

**Comment by LKaemmerling** [comment]
Duplicate of https://github.com/hetznercloud/csi-driver/issues/88
