### ISSUE TITLE
Resize did not work at hetzner cloud level

### ISSUE THREAD

**Issue by tgruenert** [hetznercloud/csi-driver#149]
Given: 
* Cluster K8s v1.18.6 with Rancher 2.4.5
* Volume 10GB bound to deployment

Action: 
* change Volume size from 10GB to 20GB

Result:
on kubernetes side everything looks quite nice:
```
Name:          sonatype-nexus
Namespace:     infrastructure
StorageClass:  hcloud-volumes
Status:        Bound
Volume:        pvc-c84c5faf-aa8c-45e4-af0a-a900f16a17db
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"sonatype-nexus","namespace":"infrastructure"},"spec...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: csi.hetzner.cloud
               volume.kubernetes.io/selected-node: worker1
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      20Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    sonatype-nexus-66c665d7c4-s5k7h
Events:
  Type    Reason                      Age    From              Message
  ----    ------                      ----   ----              -------
  Normal  FileSystemResizeSuccessful  7m30s  kubelet, worker1  MountVolume.NodeExpandVolume succeeded for volume "pvc-c84c5faf-aa8c-45e4-af0a-a900f16a17db"
```

on Hetzner Cloud nothing changed at volume level:
![grafik](https://user-images.githubusercontent.com/6465773/93578741-fb542980-f99d-11ea-9646-40720b382efa.png)

**Comment by LKaemmerling** [comment]
Hey @tgruenert,

based on what i can see with the ID (from the Screenshot) is that the volume has the correct size (20GB) as of 2020-09-18 09:53:25.734485+00 (UTC).  It looks like there was an event to the frontend missing, which triggers a reload of the frontend. If you look into the cloud console now, can you see the 20GB?

**Comment by tgruenert** [comment]
@LKaemmerling 
just for clarfication:
i´ve changed the volume size by hand after recongnizing, that it don´t do it automaticly. So, i guess,  the only way is to reproduce it step by step.

**Comment by LKaemmerling** [comment]
Hey @tgruenert,

i tried to reproduce it, but i can not trigger this. I created a sample `step by step` instruction on how i tried to reproduce it: https://github.com/LKaemmerling/hcloud-k8s-test-cases/tree/main/csi_driver/issues/149

**Comment by LKaemmerling** [comment]
Hey @tgruenert,

were you able to reproduce it again? We now have e2e tests, that test the resize case and it works on every supported k8s version (1.17 - 1.19).

If you still have the problem, feel free to reopen this issue.

- Lukas
