### ISSUE TITLE
Volume is never released on node failure

### ISSUE THREAD

**Issue by dinonovak** [hetznercloud/csi-driver#156]
HI,
deployment is creating PersistentVolumeClaim which is then attached to node where pod is running.
All works Ok.

I am simulating node failure, expecting that node should be evicted, volume release and pod reassigned to new node where volume will be attached, but this never happens.
Pod is not even moved to error state, volumeattachment is present and never deleted. It cannot be even manually deleted. When I try to delete volumeattachment manually is it is stuck in deletion process.

Please advise if there is some timeout or something that needs to be set/adjusted to allow proper release of volume if node is down.

I installed csi using
kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v1.4.0/deploy/kubernetes/hcloud-csi.yml

Thanx,
D

**Comment by LKaemmerling** [comment]
Hey @dinonovak,

could you please try our latest release v1.5.0? 
```
kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v1.5.0/deploy/kubernetes/hcloud-csi.yml
```

**Comment by dinonovak** [comment]
HI,

I was digging in the issue so I think it is more kubernetes problem.
when you make permanentvolumeclaim, it creates volumeattachment which is attatched to server where pod requesting is resides. If k8s cluster works ok, and you destroy pod, if it is recreated on new node it removes volumeattachment and claim and creates new one for required node.
If you kill a whole node (power it off), things get more complicated as k8s is not sure if it is temporarly or permanent, in theory pod should be evicted and volumeclaim and permanentvolumeclaim removed. at the moment it is not, so only way to do it currently is to cordon the node, drain it and delete volumeattachments on that node.

I am not sure if this needs to be manual process or new driver will help. Will try to see if this will work with new driver and report.
Thanx,
D

**Comment by dinonovak** [comment]
Ok,
looks like now we killed the persistent storage functionality complety.
I am unable to atatch exisitng or create a new volume.
This is what happens if I try to create volume from the scratch

If i try to create PVC I am getting:
```
% kubectl get pv                 
No resources found
```

For PVC I can see:
```
% kubectl get pvc
NAME         STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS     AGE
mssql-data   Pending      
```

if i try to troubleshoot I get
```
% kubectl describe pvc mssql-data
Name:          mssql-data
Namespace:     default
StorageClass:  hcloud-volumes
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: csi.hetzner.cloud
               volume.kubernetes.io/selected-node: test-dev-nodes2
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    mssql-deployment-7c5c495f79-rgvz9
Events:
  Type    Reason                Age                    From                         Message
  ----    ------                ----                   ----                         -------
  Normal  WaitForFirstConsumer  7m33s (x2 over 7m43s)  persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  ExternalProvisioning  2m3s (x24 over 7m21s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "csi.hetzner.cloud" or manuall
```

**Comment by dinonovak** [comment]
This is what pod is reporting

![Screenshot 2020-10-19 at 14 14 23](https://user-images.githubusercontent.com/18152490/96449643-73b83f80-1215-11eb-84d8-dc29d75e7adf.png)

**Comment by prinzdezibel** [comment]
I've the exact same problem. It used to work fine, but lately I can't deploy PVCs any more. They always end up in state pending and the event log shows
```Reason: WaitForFirstConsumer | Message:waiting for first consumer to be created before binding```
Also the volume does not appear in the Hetzner Console.

@dinonovak:  I wonder if this problem could have something to do with Rancher. It looks like you are using Rancher as well.

**Comment by LKaemmerling** [comment]
This is a design decision from k8s. See https://github.com/kubernetes/kubernetes/issues/57531#issuecomment-355139769 for more details.
