### ISSUE TITLE
docker image mismatch

### ISSUE THREAD

**Issue by nmass-betpawa** [hetznercloud/csi-driver#159]
there is no image named `v1.5.0` on docker hub only `1.5.0`
k8s manifest doesnt work

**Comment by vitobotta** [comment]
Yeah, I also tried to install this on a new cluster and got an error. Installing 1.4.0 for now.

**Comment by LKaemmerling** [comment]
Thank you, i fixed it within the deployment file and will issue a v1.5.1 within the next few minutes.

**Comment by vitobotta** [comment]
@LKaemmerling Cool, I'll wait then :)

**Comment by LKaemmerling** [comment]
@vitobotta @nmass-betpawa:

```
kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v1.5.1/deploy/kubernetes/hcloud-csi.yml
```

should work now. Thank you again!

**Comment by vitobotta** [comment]
Awesome, thanks!
