### ISSUE TITLE
hcloud-csi-controller stuck at ContainerCreating

### ISSUE THREAD

**Issue by hershkoy** [hetznercloud/csi-driver#160]
I am trying to install a kubernetes cluster on Hetzner, basically using this repo:
https://github.com/nazguluz/hcloud-k8s

The situation after I run `ansible-playbook k8s-install.yaml` is this:

$ sudo kubectl get pods --all-namespaces
```
NAMESPACE     NAME                                               READY   STATUS              RESTARTS   AGE
kube-system   cilium-h758w                                       1/1     Running             0          3h33m
kube-system   cilium-operator-64f955cb89-qcfhz                   1/1     Running             1          3h34m
kube-system   cilium-operator-64f955cb89-zg5hs                   1/1     Running             0          3h34m
kube-system   cilium-q6t74                                       1/1     Running             0          3h34m
kube-system   coredns-f9fd979d6-7h2mm                            0/1     ContainerCreating   0          3h35m
kube-system   coredns-f9fd979d6-txmzm                            0/1     ContainerCreating   0          3h35m
kube-system   etcd-master                                        1/1     Running             0          3h35m
kube-system   hcloud-cloud-controller-manager-79486b6599-xxxv7   1/1     Running             0          3h35m
kube-system   hcloud-csi-controller-0                            0/3     ContainerCreating   0          3h34m
kube-system   hcloud-csi-node-ch8b5                              2/2     Running             0          3h32m
kube-system   kube-apiserver-master                              1/1     Running             0          3h35m
kube-system   kube-controller-manager-master                     1/1     Running             1          3h35m
kube-system   kube-proxy-km2ng                                   1/1     Running             0          3h35m
kube-system   kube-proxy-wv9jh                                   1/1     Running             0          3h33m
kube-system   kube-scheduler-master                              1/1     Running             1          3h35m
```

The coredns issue seems to be resulting from the CNI issue

$ sudo kubectl describe pod coredns-f9fd979d6-7h2mm -n kube-system
```
Warning  FailedCreatePodSandBox  2m46s (x4431 over 3h32m)  kubelet, master  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "9372b270e2c7d35b37dc94f1ce33be9594115410a1e0e58dcd59f12f910181d3" network for pod "coredns-f9fd979d6-7h2mm": networkPlugin cni failed to set up pod "coredns-f9fd979d6-7h2mm_kube-system" network: unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  range is full
```

$ sudo kubectl describe pod hcloud-csi-controller-0 -n kube-system
```
Name:           hcloud-csi-controller-0
Namespace:      kube-system
Priority:       0
Node:           node-1/10.0.2.1
Start Time:     Mon, 02 Nov 2020 17:51:01 +0100
Labels:         app=hcloud-csi-controller
                controller-revision-hash=hcloud-csi-controller-7bf55d64b7
                statefulset.kubernetes.io/pod-name=hcloud-csi-controller-0
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/hcloud-csi-controller
Containers:
  csi-attacher:
    Container ID:
    Image:         quay.io/k8scsi/csi-attacher:v3.0.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
      --v=5
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hcloud-csi-token-n4grv (ro)
  csi-provisioner:
    Container ID:
    Image:         quay.io/k8scsi/csi-provisioner:v2.0.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      --provisioner=csi.hetzner.cloud
      --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
      --feature-gates=Topology=true
      --v=5
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hcloud-csi-token-n4grv (ro)
  hcloud-csi-driver:
    Container ID:
    Image:          hetznercloud/hcloud-csi-driver:1.4.0
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      CSI_ENDPOINT:  unix:///var/lib/csi/sockets/pluginproxy/csi.sock
      HCLOUD_TOKEN:  <set to the key 'token' in secret 'hcloud-csi'>  Optional: false
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hcloud-csi-token-n4grv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  hcloud-csi-token-n4grv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hcloud-csi-token-n4grv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>
```

I tried getting logs from the hcloud-csi-controller-0 but all of them are not just stuck and not return anything to console:

```
sudo kubectl logs hcloud-csi-controller-0 -n kube-system -c csi-attacher
sudo kubectl logs hcloud-csi-controller-0 -n kube-system -c csi-provisioner
sudo kubectl logs hcloud-csi-controller-0 -n kube-system -c hcloud-csi-driver
```

What can be the cause of this issue?

**Comment by LKaemmerling** [comment]
The CSI driver doesn't have a connection to the Internet, because of your CNI issue. When the CNI issue is fixed, it should recover/work.

**Comment by hershkoy** [comment]
I upgraded to CSI driver 1.5.1 and now after restarting everything at least I was able to connect the other node:

```
$ kubectl get nodes
NAME     STATUS   ROLES    AGE     VERSION
master   Ready    master   6h59m   v1.19.0
node-1   Ready    <none>   6h57m   v1.19.0
```

But the kube system pods are still stuck

$ kubectl get pods -n kube-system
```
NAME                                               READY   STATUS              RESTARTS   AGE
cilium-mfbng                                       1/1     Running             0          7h
cilium-operator-64f955cb89-bjvj4                   1/1     Running             0          7h
cilium-operator-64f955cb89-p5gn9                   1/1     Running             0          7h
cilium-wrj7k                                       1/1     Running             0          6h59m
coredns-f9fd979d6-cszrq                            0/1     ContainerCreating   0          7h1m
coredns-f9fd979d6-kvbrt                            0/1     ContainerCreating   0          7h1m
etcd-master                                        1/1     Running             0          7h1m
hcloud-cloud-controller-manager-79486b6599-p69zs   1/1     Running             0          7h
hcloud-csi-controller-0                            0/3     ContainerCreating   0          7h
hcloud-csi-node-6zw58                              2/2     Running             0          6h58m
kube-apiserver-master                              1/1     Running             0          7h1m
kube-controller-manager-master                     1/1     Running             0          7h1m
kube-proxy-fg4nq                                   1/1     Running             0          6h59m
kube-proxy-lmbfl                                   1/1     Running             0          7h1m
kube-scheduler-master                              1/1     Running             0          7h1m
```

$ sudo kubectl describe pod hcloud-csi-controller-0 -nkube-system

```
Name:           hcloud-csi-controller-0
Namespace:      kube-system
Priority:       0
Node:           node-1/10.0.2.1
Start Time:     Tue, 03 Nov 2020 10:54:14 +0100
Labels:         app=hcloud-csi-controller
                controller-revision-hash=hcloud-csi-controller-784c5dbf99
                statefulset.kubernetes.io/pod-name=hcloud-csi-controller-0
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/hcloud-csi-controller
Containers:
  csi-attacher:
    Container ID:
    Image:         quay.io/k8scsi/csi-attacher:v3.0.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
      --v=5
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hcloud-csi-token-kkvqh (ro)
  csi-provisioner:
    Container ID:
    Image:         quay.io/k8scsi/csi-provisioner:v2.0.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      --provisioner=csi.hetzner.cloud
      --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
      --feature-gates=Topology=true
      --v=5
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hcloud-csi-token-kkvqh (ro)
  hcloud-csi-driver:
    Container ID:
    Image:          hetznercloud/hcloud-csi-driver:1.5.1
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      CSI_ENDPOINT:  unix:///var/lib/csi/sockets/pluginproxy/csi.sock
      HCLOUD_TOKEN:  <set to the key 'token' in secret 'hcloud-csi'>  Optional: false
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hcloud-csi-token-kkvqh (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  hcloud-csi-token-kkvqh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hcloud-csi-token-kkvqh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                       From             Message
  ----     ------                  ----                      ----             -------
  Normal   SandboxChanged          13m (x10913 over 6h43m)   kubelet, node-1  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  3m6s (x11148 over 6h42m)  kubelet, node-1  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "07116272c35ea1ea75aabf507265824d08b0fa47bb81797b52adb7c7425e3385" network for pod "hcloud-csi-controller-0": networkPlugin cni failed to set up pod "hcloud-csi-controller-0_kube-system" network: unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  range is full
```
$ sudo kubectl logs hcloud-csi-controller-0 -n kube-system -c hcloud-csi-driver
```
Error from server: Get "https://10.0.2.1:10250/containerLogs/kube-system/hcloud-csi-controller-0/hcloud-csi-driver": dial tcp 10.0.2.1:10250: i/o timeout
```

What do I need to do to solve the CNI issue?

**Comment by jekakm** [comment]
https://github.com/cilium/cilium/issues/9793
Try to look at this

**Comment by hershkoy** [comment]
Ok. Added the `blacklist-conflicting-routes=false` to cilium configuration and there is a slight improvement

Coredns pod is now ok, but still some errors on the csi controller

$ sudo kubectl get pods --all-namespaces
NAMESPACE     NAME                                               READY   STATUS             RESTARTS   AGE
kube-system   cilium-d6n7r                                       1/1     Running            0          6h48m
kube-system   cilium-ldrxh                                       1/1     Running            0          6h49m
kube-system   cilium-operator-64f955cb89-d6f8n                   1/1     Running            2          6h49m
kube-system   cilium-operator-64f955cb89-lsm4m                   1/1     Running            3          6h49m
kube-system   coredns-f9fd979d6-bnjjx                            1/1     Running            0          6h49m
kube-system   coredns-f9fd979d6-bx6zf                            1/1     Running            0          6h49m
kube-system   etcd-master                                        1/1     Running            2          6h50m
kube-system   hcloud-cloud-controller-manager-79486b6599-2wm6r   1/1     Running            0          6h49m
kube-system   hcloud-csi-controller-0                            1/3     CrashLoopBackOff   160        6h49m
kube-system   hcloud-csi-node-rq89f                              2/2     Running            0          6h46m
kube-system   kube-apiserver-master                              1/1     Running            3          6h50m
kube-system   kube-controller-manager-master                     1/1     Running            4          6h50m
kube-system   kube-proxy-g7ctd                                   1/1     Running            0          6h49m
kube-system   kube-proxy-hsbg2                                   1/1     Running            0          6h48m
kube-system   kube-scheduler-master                              1/1     Running            4          6h50m
```

Logs from the controller are not available

```
k8s@master:~$ sudo kubectl logs hcloud-csi-controller-0 -n kube-system -c csi-attacher
Error from server: Get "https://10.0.2.1:10250/containerLogs/kube-system/hcloud-csi-controller-0/csi-attacher": dial tcp 10.0.2.1:10250: i/o timeout
k8s@master:~$ sudo kubectl logs hcloud-csi-controller-0 -n kube-system -c csi-provisioner
Error from server: Get "https://10.0.2.1:10250/containerLogs/kube-system/hcloud-csi-controller-0/csi-provisioner": dial tcp 10.0.2.1:10250: i/o timeout
k8s@master:~$ sudo kubectl logs hcloud-csi-controller-0 -n kube-system -c hcloud-csi-driver
Error from server: Get "https://10.0.2.1:10250/containerLogs/kube-system/hcloud-csi-controller-0/hcloud-csi-driver": dial tcp 10.0.2.1:10250: i/o timeout
```

There is no connectivity to the other server (though I checked before installing kubernetes and there was):
```
k8s@master:~$ ping 10.0.2.1
PING 10.0.2.1 (10.0.2.1) 56(84) bytes of data.
^C
--- 10.0.2.1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2045ms
```

k8s@master:~$ sudo kubectl describe pod hcloud-csi-controller-0 -nkube-system 
```                                                                                   
Name:         hcloud-csi-controller-0                                                                                                                            
Namespace:    kube-system                                                                                                                                        
Priority:     0                                                                                                                                                  
Node:         node-1/10.0.2.1                                                                                                                                    
Start Time:   Wed, 04 Nov 2020 10:07:35 +0100                                                                                                                    
Labels:       app=hcloud-csi-controller                                                                                                                          
              controller-revision-hash=hcloud-csi-controller-784c5dbf99                                                                                          
              statefulset.kubernetes.io/pod-name=hcloud-csi-controller-0                                                                                         
Annotations:  <none>                                                                                                                                             
Status:       Running                                                                                                                                            
IP:           10.0.1.111                                                                                                                                         
IPs:                                                                                                                                                             
  IP:           10.0.1.111                                                                                                                                       
Controlled By:  StatefulSet/hcloud-csi-controller                                                                                                                
Containers:                                                                                                                                                      
  csi-attacher:                                                                                                                                                  
    Container ID:  docker://ba30135603489243f6bb7871ba98481228a8f1cfd733fea16406ba1509741754                                                                     
    Image:         quay.io/k8scsi/csi-attacher:v3.0.0                                                                                                            
    Image ID:      docker-pullable://quay.io/k8scsi/csi-attacher@sha256:f141eca4d60481b2a460cbd6720a80e40bb289b0fc7a495f5e80d88eca31d9ba                         
    Port:          <none>                                                                                                                                        
    Host Port:     <none>                                                                                                                                        
    Args:                                                                                                                                                        
      --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock                                                                                                    
      --v=5                                                                                                                                                      
    State:          Running                                                                                                                                      
      Started:      Wed, 04 Nov 2020 10:07:44 +0100                                                                                                              
    Ready:          True                                                                                                                                         
    Restart Count:  0                                                                                                                                            
    Environment:    <none>                                                                                                                                       
    Mounts:                                                                                                                                                      
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)                                                                                                     
      /var/run/secrets/kubernetes.io/serviceaccount from hcloud-csi-token-pd5wz (ro)                                                                             
  csi-provisioner:                                                                                                                                               
    Container ID:  docker://3083a76204c50da142d4262a09204f8ce374f4bad97e092883ecbe5ac40e6a44                                                                     
    Image:         quay.io/k8scsi/csi-provisioner:v2.0.0                                                                                                         
    Image ID:      docker-pullable://quay.io/k8scsi/csi-provisioner@sha256:bc6e23058c2b0b610c62851dbd87f3b32bc6d4f10e75657ab36253a7106dbfea                      
    Port:          <none>                                                                                                                                        
    Host Port:     <none>                                                                                                                                        
    Args:                                                                                                                                                        
      --provisioner=csi.hetzner.cloud                                                                                                                            
      --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock                                                                                                    
      --feature-gates=Topology=true                                                                                                                              
      --v=5                                                                                                                                                      
    State:          Waiting                                                                                                                                      
      Reason:       CrashLoopBackOff                                                                                                                             
    Last State:     Terminated                                                                                                                                   
      Reason:       Error                                                                                                                                        
      Exit Code:    2                                                                                                                                            
      Started:      Wed, 04 Nov 2020 17:03:16 +0100                                                                                                              
      Finished:     Wed, 04 Nov 2020 17:03:16 +0100                                                                                                              
    Ready:          False                                                                                                                                        
    Restart Count:  86                                                                                                                                           
    Environment:    <none>                                                                                                                                       
    Mounts:                                                                                                                                                      
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)                                                                                                     
      /var/run/secrets/kubernetes.io/serviceaccount from hcloud-csi-token-pd5wz (ro)                                                                             
  hcloud-csi-driver:                                                                                                                                             
    Container ID:   docker://4579e5866af9da240813b4ee531677f5daf31a28329240bfa481864dbd4ab880                                                                    
    Image:          hetznercloud/hcloud-csi-driver:1.5.1                                                                                                         
    Image ID:       docker-pullable://hetznercloud/hcloud-csi-driver@sha256:41dce5b33644629b069170bb2b2087dd92b9238c5bc16de0a1bfdfbf78e318ba                     
    Port:           <none>                                                                                                                                       
    Host Port:      <none>                                                                                                                                       
    State:          Waiting                                                                                                                                      
      Reason:       CrashLoopBackOff                                                                                                                             
    Last State:     Terminated                                                                                                                                   
      Reason:       Error                                                                                                                                        
      Exit Code:    1                                                                                                                                            
      Started:      Wed, 04 Nov 2020 17:02:45 +0100                                                                                                              
      Finished:     Wed, 04 Nov 2020 17:03:15 +0100                                                                                                              
    Ready:          False                                                                                                                                        
    Restart Count:  78                                                                                                                                           
    Environment:                                                                                                                                                 
      CSI_ENDPOINT:  unix:///var/lib/csi/sockets/pluginproxy/csi.sock                                                                                            
      HCLOUD_TOKEN:  <set to the key 'token' in secret 'hcloud-csi'>  Optional: false                                                                            
    Mounts:                                                                                                                                                      
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)                                                                                                     
      /var/run/secrets/kubernetes.io/serviceaccount from hcloud-csi-token-pd5wz (ro)                                                                             
Conditions:                                                                                                                                                      
  Type              Status                                                                                                                                       
  Initialized       True                                                                                                                                         
  Ready             False                                                                                                                                        
  ContainersReady   False                                                                                                                                        
  PodScheduled      True                                                                                                                                         
Volumes:                                                                                                                                                         
  socket-dir:                                                                                                                                                    
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)                                                                                    
    Medium:                                                                                                                                                      
    SizeLimit:  <unset>                                                                                                                                          
  hcloud-csi-token-pd5wz:                                                                                                                                        
    Type:        Secret (a volume populated by a Secret)                                                                                                         
    SecretName:  hcloud-csi-token-pd5wz                                                                                                                          
    Optional:    false                                                                                                                                           
QoS Class:       BestEffort                                                                                                                                      
Node-Selectors:  <none>                                                                                                                                          
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s                                                                                       
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s                                                                                     
Events:                                                                                                                                                          
  Type     Reason   Age                     From             Message                                                                                             
  ----     ------   ----                    ----             -------                                                                                             
  Normal   Pulled   31m (x83 over 6h47m)    kubelet, node-1  (combined from similar events): Container image "quay.io/k8scsi/csi-provisioner:v2.0.0" already pres
t on machine                                                                                                                                                     
  Warning  BackOff  6m (x1772 over 6h54m)   kubelet, node-1  Back-off restarting failed container                                                                
  Warning  BackOff  56s (x2026 over 6h55m)  kubelet, node-1  Back-off restarting failed container                                                                
```

Joining a node to the master is not working (maybe because of the network connectivity issue) 

Any idea how to proceed?

**Comment by hershkoy** [comment]
Something is adding these routes:

![image](https://user-images.githubusercontent.com/13259380/98167788-4d232580-1ef2-11eb-9a3b-abdaee38f4a5.png)


I suspect kube-controller-manager-master:

![image](https://user-images.githubusercontent.com/13259380/98167748-40063680-1ef2-11eb-930a-6a6790dea3f8.png)

Before they were added, the network connection was ok. 
but it is not in the code of repo. The 192.168.* is going nowhere, so I don't know where it is coming from

**Comment by LKaemmerling** [comment]
@hershkoy The ansible repo you linked contains this IP: https://github.com/nazguluz/hcloud-k8s/blob/master/roles/kube-master/files/hcloud-controller.yaml#L62 

You need to change this to something in your `10.0.0.0/8` range, then it should work (after you reinit the cluster).

**Comment by hershkoy** [comment]
I managed to install Kubernetes eventually using another repo, based on Calico, not cilium (and other changes)
https://github.com/marriva/hcloud-k8s
