### ISSUE TITLE
[Question] Meet prerequisites?

### ISSUE THREAD

**Issue by Berndinox** [hetznercloud/csi-driver#17]
Hy, i'm new to Kubernetes...

how can i enable the required prerequisites:

--feature-gates=CSINodeInfo=true,CSIDriverRegistry=true
--allow-privileged=true

I have create a Test-Env with kudeadm. 1 Master 2 Worker. 
Thanks! 
BR Bernd

**Comment by laurawadden** [comment]
With Kubernetes 1.13, [--allow-privileged=true is the default setting](https://kubernetes-csi.github.io/docs/print.html#enable-privileged-pods).

To set the feature gates, I added the following to my kubelet-config-1.13 configMap:

```
featureGates:
  CSINodeInfo: true
  CSIDriverRegistry: true
```
Apparently kubelet checks for changes every 20 seconds and restarts with the new configuration. It was a guess, given the[ kubelet manifest options defined here](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) and the state of my kubelet configMap. It's worked so far.

I used kubeadm to setup my cluster.

I am still curious how/where to change the master api-server.

**Comment by Berndinox** [comment]
Hy Laura,

thanks for clarification. i've created the configmap.

however, I still got:
`  Warning  FailedMount             7s (x6 over 22s)    kubelet, k8s-2           MountVolume.NewMounter initialization failed for volume "pvc-43bf4e04-2eaf-11e9-8909-9600001ae4e5" : driver name csi.hetzner.cloud not found in the list of registered CSI drivers`

Seems like api-server config is missed, as you have mentioned.
May someone else can give a hint?

**Comment by laurawadden** [comment]
I just added '--feature-gates=CSINodeInfo=true,CSIDriverRegistry=true' to the list of flags in '/etc/kubernetes/manifests/kube-apiserver.yaml' on the master node and the apiserver restarted automatically with the new configuration.

**Comment by steffenmllr** [comment]
Just ran into the same problem. @laurawadden did you find a solution ?

**Comment by laurawadden** [comment]
I see this error in my csi-provisioner log, so I still don't think I have the prereqs setup properly:

```
 1 topology.go:171] error getting CSINodeInfo for selected node "node-1234": csinodeinfos.csi.storage.k8s.io "node-1234" not found; proceeding to provision without topology information
```

**Comment by laurawadden** [comment]
> Just ran into the same problem. @laurawadden did you find a solution ?

[See above](https://github.com/hetznercloud/csi-driver/issues/17#issuecomment-462685563), I updated my answer. I just needed to download the edited kubelet config to each node and restart the kubelet. On my test setup I did those steps manually.
