### ISSUE TITLE
Unify Secret Name across hetznercloud kubernetes projects

### ISSUE THREAD

**Issue by NotANormalNerd** [hetznercloud/csi-driver#173]
Hey Guy,

I think it would be beneficial if we could unify the secret names across the projects csi-driver & cloud-controller-manager.
Currently it is hcloud-csi for csi-driver and hcloud for controller manager. Since a Kubernetes Project can only live in one Project, it would be usefull to use the same secret in both projects.

Thanks for reading and all the work. 

Greetings Dennis

**Comment by LKaemmerling** [comment]
Hey @NotANormalNerd,

thank you for your request. We already have this on our desk. This is basically a breaking change (for existing clusters), so it would require a new major release. At the moment we don't see a reason why we should release a new major release only for this specific change.
