### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by identw** [hetznercloud/csi-driver#174]
same problem #101 @andy812
```
level=debug ts=2021-01-20T08:41:51.566438303Z msg="getting instance id from metadata service"
level=debug ts=2021-01-20T08:41:51.866177585Z msg="fetching server"
level=error ts=2021-01-20T08:42:02.667207353Z msg="failed to fetch server" err="Get \"https://api.hetzner.cloud/v1/servers/4660682\": net/http: TLS handshake timeout"
```
This is not a network problem. Since I added a debug container to the same pod, and everything is fine with the network in it
For example:
```
$ k logs -c hcloud-csi-driver hcloud-csi-controller-8599c66596-wq682 
level=debug ts=2021-01-20T08:41:51.566438303Z msg="getting instance id from metadata service"
level=debug ts=2021-01-20T08:41:51.866177585Z msg="fetching server"
level=error ts=2021-01-20T08:42:02.667207353Z msg="failed to fetch server" err="Get \"https://api.hetzner.cloud/v1/servers/4660682\": net/http: TLS handshake timeout"

$ k exec -it hcloud-csi-controller-8599c66596-wq682 -c debug -- curl https://api.hetzner.cloud/v1/servers/4660682
{
  "error": {
    "message": "unable to authenticate",
    "code": "unauthorized",
    "details": null
  }
}
```
![image](https://user-images.githubusercontent.com/22338503/105150070-19858e00-5b26-11eb-920c-5d298d066f98.png)

**Comment by LKaemmerling** [comment]
Hey @identw,

can you provide a few more information about your Cluster Setup? For me it looks like a Networking Issue. The CSI Driver uses the same network path as all other requests within your pods, so when curl works, the CSI driver should work aswell.

**Comment by identw** [comment]
@LKaemmerling 
Thank you

Found a problem, it looks like I allocated too few resources to the controller, because of this, the controller was executing requests for a very long time. The problem was not a network one.
