### ISSUE TITLE
Unable to connect to `unix:///csi/csi.sock`

### ISSUE THREAD

**Issue by cfra** [hetznercloud/csi-driver#175]
I am setting up a cluster using the Hetzner Cloud CSI driver.

On one node, the driver fails to start up with the following log output:

```console
I0121 18:59:29.644417       1 main.go:110] Version: v1.3.0-0-g6e9fff3e
I0121 18:59:29.645485       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0121 18:59:29.645880       1 connection.go:151] Connecting to unix:///csi/csi.sock
W0121 18:59:38.156443       1 connection.go:170] Still connecting to unix:///csi/csi.sock
W0121 18:59:48.156969       1 connection.go:170] Still connecting to unix:///csi/csi.sock
W0121 18:59:58.156521       1 connection.go:170] Still connecting to unix:///csi/csi.sock
W0121 19:00:08.156329       1 connection.go:170] Still connecting to unix:///csi/csi.sock
W0121 19:00:18.156366       1 connection.go:170] Still connecting to unix:///csi/csi.sock
```

On the other nodes, the driver seems to be operating fine:

```console
I0121 19:00:41.261771       1 main.go:110] Version: v1.3.0-0-g6e9fff3e
I0121 19:00:41.262594       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0121 19:00:41.262980       1 connection.go:151] Connecting to unix:///csi/csi.sock
I0121 19:00:44.486160       1 main.go:127] Calling CSI driver to discover driver name
I0121 19:00:44.486242       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0121 19:00:44.486259       1 connection.go:181] GRPC request: {}
I0121 19:00:44.501145       1 connection.go:183] GRPC response: {"name":"csi.hetzner.cloud","vendor_version":"1.5.1"}
I0121 19:00:44.502242       1 connection.go:184] GRPC error: <nil>
I0121 19:00:44.502369       1 main.go:137] CSI driver name: "csi.hetzner.cloud"
I0121 19:00:44.502880       1 node_register.go:51] Starting Registration Server at: /registration/csi.hetzner.cloud-reg.sock
I0121 19:00:44.503238       1 node_register.go:60] Registration Server started at: /registration/csi.hetzner.cloud-reg.sock
I0121 19:00:44.750210       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0121 19:00:44.781306       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
I0121 19:00:46.749798       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0121 19:00:46.790566       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

Any idea how I can debug this?

**Comment by cfra** [comment]
This turned out to be a network issue.

**Comment by kiwinesian** [comment]
Hi @cfra 

Mind if I ask what network configuration did you change?
I'm experiencing the same issue
2 worker nodes - 1 seems to be fine but one is just stuck here. :(

**Comment by cfra** [comment]
Sorry for not providing a more extensive explanation in January. I did not want to withhold information, I just felt the resolution did not really have much of a relation with the csi-driver.

If I remember correctly, I was running a setup with a floating IP address using [hcloud-fip-controller](https://github.com/cbeneke/hcloud-fip-controller) that required the floating IP to be configured on all worker nodes of the cluster.

The way I had configured the /32 for the floating IP on the worker nodes, they would use that IP as source IP when attempting to connect, leading to failure on all nodes except the one with the floating IP currently assigned.

The solution for that problem was a change in the IP configuration, I think either by assigning the `/32` to `eth0` instead of `lo` or by adding `scope link` to the IP assignment.

This way, the nodes used their individual IP for connecting instead of the floating IP and everything worked as intended.

**Comment by kiwinesian** [comment]
Hi @cfra 

Seems like I am setting up the exact configuration! what are the odds.
I am also using the https://github.com/cbeneke/hcloud-fip-controller and configuring it on all the worker nodes.

On all the worker nodes (also the master node), the following file has been updated as per the floating IP `/etc/network/interfaces.d/60-floating-ip.cfg`
```
auto eth0:1
iface eth0:1 inet static
  address x.x.x.x
  netmask 32
```
where x.x.x.x = the floating IP in Hetzner

Is the next step to assign the floating IP to the node? at the moment, the floating IP remained unassigned. :( 

Spent the entire weekend with this to nothing - really hope there is a light at the end of this tunnel - so thank YOU! 🙏

**Comment by cfra** [comment]
If the IP is not yet assigned, you are probably facing another issue, though you might run into the issue after reboot.

You could try checking what is going on using tcpdump and/or strace. (As you might be able to tell from my question in January, I never managed to find any more elaborate ways of debugging the csi-driver)

**Comment by kiwinesian** [comment]
thank you @cfra !

I overwrote the `fip-rbac.yaml` and the `fip-deployment.yaml` with the one from the repo and now the floating IP is assigned automatically!
Although, it also assigned all floating IPs that were prior to the deployment - very weird.

I'm starting to wonder if it's not compatible with the latest kubernetes.
