### ISSUE TITLE
Consider making topology awareness optional

### ISSUE THREAD

**Issue by thcyron** [hetznercloud/csi-driver#18]
It requires the `Topology` feature gate which is alpha, and requiring users to use alpha features is suboptimal.

**Comment by githubixx** [comment]
At least for `quay.io/k8scsi/csi-provisioner:v1.2.0` this changed to beta: `Topology=true|false (BETA - default=false)`. That was released 5 days ago. `hcloud-csi.yml` uses `csi-provisioner:v1.0.1` currently.

**Comment by costela** [comment]
Since #43 got merged, maybe this isn't needed after all?
