### ISSUE TITLE
Possibility to reference pre-existing volume

### ISSUE THREAD

**Issue by jangraefen** [hetznercloud/csi-driver#183]
Hello,

maybe I just did not read the right documentation or have not found the piece of code that does it, but it seems like it is not possible to annotate a PVC to customize the volume that is created.

Something similar is possible for load balancers, where the `load-balancer.hetzner.cloud/name` annotation on a service controls the load balancer that is created. If such a load balancer already exists before-hand, the existing one is re-used. I am asking myself if the same could be achieved for volumes as well?

With kind regard 🙂.

**Comment by marcinziolo** [comment]
+1.

Exactly I'm also looking forward for this feature.
I have DB data stored on hetzner volumes by PVC. 
I would like to reuse them when creating cluster anew.

**Comment by jangraefen** [comment]
Good thing you commented. I forgot that I actually found a solution: https://github.com/hetznercloud/csi-driver/issues/146
Still, I think this should be documented better 🙂.

**Comment by marcinziolo** [comment]
Thanks :)
