### ISSUE TITLE
Volume stucks in pending state

### ISSUE THREAD

**Issue by sullrich84** [hetznercloud/csi-driver#188]
Hello,

After upgrading rancher and kubernetes, I can't claim `PVs` anymore. Volume always stucks in the pending state:

```
waiting for a volume to be created, either by external provisioner "csi.hetzner.cloud" or manually created by system administrator
```

I'm using:
CSI-Driver: 1.5.1
Rancher 2.2.5
Kubernetes Version: v1.19.8

Any ideas what could cause this issue?
Best regards :)

**Comment by LKaemmerling** [comment]
Hey @sullrich84,

can you have a look at the logs from the csi-driver (controller)?

**Comment by sullrich84** [comment]
Hey @LKaemmerling,

thanks for the reply! It seems like the services `csi-provisioner` and `hcloud-csi-driver` are crashing continuously. 

```
quay.io/k8scsi/csi-provisioner:v1.6.0:

W0318 06:31:25.636523       1 deprecatedflags.go:53] Warning: option provisioner="csi.hetzner.cloud" is deprecated and has no effect
I0318 06:31:25.636847       1 feature_gate.go:243] feature gates: &{map[Topology:true]}
I0318 06:31:25.636963       1 csi-provisioner.go:107] Version: v1.6.0-0-g321fa5c1c
I0318 06:31:25.637037       1 csi-provisioner.go:121] Building kube configs for running in cluster...
F0318 06:31:55.640944       1 csi-provisioner.go:141] Error getting server version: Get https://10.43.0.1:443/version?timeout=32s: dial tcp 10.43.0.1:443: i/o timeout

hetznercloud/hcloud-csi-driver:1.5.1:
[no logs]
```

**Comment by LKaemmerling** [comment]
Hey @sullrich84,

looks like the in cluster networking does not work correctly, can you check this?

**Comment by sullrich84** [comment]
You were right, after restarting the node and reinstalling the `csi-driver`, the `hcloud-csi-driver` is now responding to liveness probes and `PVC` claims. 

Thanks alot for your time and support!
