### ISSUE TITLE
Recognition of root servers: an idea

### ISSUE THREAD

**Issue by uykusuz** [hetznercloud/csi-driver#189]
Dear Hetzner Team,

similar to [this issue](https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/172) we had issues in a hybrid cluster getting the CSI driver to work. In contrast to the linked issue it's easier to fix: don't deploy the CSI driver to the root server.

We did this by introducing a new label and corresponding taint: [here](https://github.com/hetznercloud/csi-driver/compare/master...xelonic:root-server-ignore).

What do you think of it? I could imagine other people run into the same issues.

**Comment by fourstepper** [comment]
I think it would be awesome if you sent a pull request - I would be a fan of having this option available to me

**Comment by ieugen** [comment]
Hi,

There is an issue with this approach.
It does not seem to work to add the taint.

```
kubectl taint node fn1 instance.hetzner.cloud/is-root-server:true
error: invalid taint effect: true, unsupported taint effect
See 'kubectl taint -h' for help and examples

k version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-10T11:48:48Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10+k3s1", GitCommit:"72e8196c9b9eb277f56951db6d2d9e5f9f70feac", GitTreeState:"clean", BuildDate:"2021-04-16T18:36:38Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jleni** [comment]
Yes, it should not be a taint but a label

```
kubectl label nodes <NODE> instance.hetzner.cloud/is-root-server=true
```
