### ISSUE TITLE
Incorrect tag on dockerhub

### ISSUE THREAD

**Issue by SergeyKons** [hetznercloud/csi-driver#193]
Currently there is no image tagged as hetznercloud/hcloud-csi-driver:1.5.2 but there is
hetznercloud/hcloud-csi-driver:v1.5.2
Looks like a typo because it brokes version consistency

https://hub.docker.com/r/hetznercloud/hcloud-csi-driver/tags

**Comment by LKaemmerling** [comment]
Hey @SergeyKons,

thank you for the report. The issue was fixed with the MR #192. I‘m sorry that this happened. I will investigate tomorrow morning why this happened at all. I‘m sorry!
