### ISSUE TITLE
Back again to `Still connecting to unix:///csi/csi.sock` issue

### ISSUE THREAD

**Issue by kiwinesian** [hetznercloud/csi-driver#206]
Hi everyone,

I've spent an entire weekend trying to solve this but gave up.
Partly because I'm still new in the k8s so I can't really figure out the right configuration for it.

I went through few other threads with similar issue, but either no resolution was provided or (well I think) may not be relevant to my scenario.

Here is what I did so far,
1. Ubuntu 20.04
2. Kubernetes 1.21
3. Cilium 1.10.1 installed via Helm
4. csi-driver is 1.5.3
5. `ufw` is disabled

Server config:
1 x master CPX11
2 x worker CX21
Subnet is 10.0.0.0/8
No Hetzner Firewall

Below are the commands that I ran to create the k8s
`kubeadm init --pod-network-cidr=10.217.0.0/16 --apiserver-cert-extra-sans=10.0.0.1 --ignore-preflight-errors=NumCPU`

Replaced the following field in the `https://raw.githubusercontent.com/hetznercloud/csi-driver/master/deploy/kubernetes/hcloud-csi.yml`
1. `"--cluster-cidr=10.217.0.0/16"`

Everything seems to work except the `hcloud-csi-node`.
2 out of 3 always `CrashLoopBackOff`

Further investigation:
Node 'worker-0' and 'master-0', `quay.io/k8scsi/csi-node-driver-registrar` docker log
```
1 main.go:110] Version: v1.3.0-0-g6e9fff3e
1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
1 connection.go:151] Connecting to unix:///csi/csi.sock
1 connection.go:170] Still connecting to unix:///csi/csi.sock
1 connection.go:170] Still connecting to unix:///csi/csi.sock
```

2. Node 'worker-0' and 'master-0', `quay.io/k8scsi/livenessprobe` docker log
```
1 connection.go:151] Connecting to unix:///csi/csi.sock
1 connection.go:170] Still connecting to unix:///csi/csi.sock
```

3. Node 'worker-1' seems to be fine for some reason
```
1 connection.go:151] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
1 main.go:86] calling CSI driver to discover driver name
1 main.go:91] CSI driver name: "csi.hetzner.cloud"
1 main.go:100] Serving requests to /healthz on: 0.0.0.0:9808
1 main.go:53] Sending probe request to CSI driver "csi.hetzner.cloud"
1 main.go:71] Health check succeeded
```

There was some comments that it could be Cilium configuration, but I installed mine via Helm so I'm not sure if I might be missing something?

Any help will be greatly appreciated!
Spent the whole weekend without getting anywhere :( 

![image](https://user-images.githubusercontent.com/12476195/123587149-b2d26380-d79a-11eb-97c5-95b3c036a6bf.png)

**Comment by LKaemmerling** [comment]
Hey @kiwinesian,

please make sure that those nodes can access the Hetzner Cloud API. (You can try it with a pod on that node and then do a curl against https://api.hetzner.cloud. This should return a 404.

**Comment by kiwinesian** [comment]
Hi Lukas,

Yes, I read something about this and was able to curl the
https://api.herzner.cloud and got the 404.
I was able to do it from all 3 servers, but thought it didnt mean anything
because it was 404, but I guess it does matter.

Any other thoughts?
Should I try to use version 1.5.1 driver?

I'm so puzzled at this point. :(

**Comment by LKaemmerling** [comment]
Hey @kiwinesian,

did you try it on the node or within a pod in the cluster? On the node itself it should work, but it also should work in a pod in the cluster.

**Comment by kiwinesian** [comment]
Oww..
I guess I was doing it from the server = node.

When you say pod, do I just `docker exec` to any docker that belongs to the
pod? Or there is actually a kubectl command that can get me into the pod?
Sorry for the noob question, it is kinda 2nd month deep into the k8s world

**Comment by LKaemmerling** [comment]
You can try:

```
kubectl exec -it <a-pod-on-the-node> /bin/bash  <or /bin/sh>

**Comment by kiwinesian** [comment]
Oh thank you!!!

I will give it a go today.
Will reach back with the results.

**Comment by kiwinesian** [comment]
thanks @LKaemmerling !

I tried but it doesn't quite work - maybe the feature is deprecated?
I tried both to a `Running` pod and the pod `CrashLoopBackOff` and they both resulted to the same error message below :(
Same results with either `/bin/sh` or `/bin/bash`

**`CrashLoopBackOff` pod**
```
root@deb10-ansible-01:~/development-hcloud-k8s# kubectl exec -it hcloud-csi-node-w5lkp /bin/sh -n kube-system
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "csi-node-driver-registrar" out of: csi-node-driver-registrar, hcloud-csi-driver, liveness-probe
Error from server: error dialing backend: dial tcp 10.0.2.2:10250: i/o timeout
```

**`Running` pod**
```
root@deb10-ansible-01:~/development-hcloud-k8s# kubectl exec -it cilium-cp2x9 /bin/sh -n kube-system
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
Error from server: error dialing backend: dial tcp 10.0.2.1:10250: i/o timeout
```

I can go to a node and `docker exec` to a running container, if that is a similar behavior?

Thank you so much for all the guidance so far! 🙏

**Comment by LKaemmerling** [comment]
@kiwinesian and there you see the issue 😉 the I/o timeout should not happen so there is a misconfiguration on those nodes. Are they attached to the same cloud network as the other servers?

**Comment by kiwinesian** [comment]
aha.. thank you!! 🙏 
have to say network is not really my strength!
Appreciate for the pointers!

They are in the same Cloud Network, 10.0.0.0/8
![image](https://user-images.githubusercontent.com/12476195/123696186-50b44580-d810-11eb-89c4-4160baab7b9f.png)

But is split to 2 subnets: master (10.0.1.x) and worker (10.0.2.x)
![image](https://user-images.githubusercontent.com/12476195/123696275-69bcf680-d810-11eb-9ee5-71a173b75cfc.png)

I also have a dedicated `ansible` server to build/ destroy the sandbox and this is where I usually execute the `kubectl` command.
This was server was not in the network initially - just tried to add it to the same subnet as the worker, but same error. :(
![image](https://user-images.githubusercontent.com/12476195/123696353-85c09800-d810-11eb-8e33-291dff76812d.png)

soooo confusing this k8s.. 😱 
really appreciate the help! 🙏

**Comment by kiwinesian** [comment]
I am also using this built that includes `https://github.com/cbeneke/hcloud-fip-controller` to assign the floating IP.
Not sure if change the whole ball game? =\

**Comment by LKaemmerling** [comment]
I guess the network configuration is wrong then. Try to put everything in one subnet, at least this should work with the default cilium config.

**Comment by kiwinesian** [comment]
Hi @LKaemmerling 

And it is solved! thank you so much for providing all the pointers that helped me to troubleshoot the root cause.
Below is the summary of what went wrong:
1. Switched back to Ubuntu 18.04 from Ubuntu 20.04 (there is an existing issue now, will create another thread to discuss this particular one)
2. If using Ubuntu 20.04, they use a different `network-manager`, see https://docs.hetzner.com/cloud/floating-ips/persistent-configuration/
3. Default Cilium didn't work. Ended up using a custom `.yaml` to run the Cilium build.

thank YOU!!
