### ISSUE TITLE
Question: Does CSI driver working if I use it for Robot baremetal machines w/ Kubernetes?

### ISSUE THREAD

**Issue by gris-gris** [hetznercloud/csi-driver#239]
What if I have a plan to have hybrid Kubernetes cluster, that includes Hcloud instances and Baremetal Robot servers connected via vSwitch? It will work with CSI driver?

**Comment by samcday** [comment]
@gris-gris yep, as per the [README](https://github.com/hetznercloud/csi-driver#integration-with-root-servers) you'll need to ensure your bare metal nodes don't have the CSI driver DaemonSet scheduled there:

```sh
kubectl taint node <node name> instance.hetzner.cloud/is-root-server:true
```

**Comment by gris-gris** [comment]
So I can mount PVCs created in Hetzner volumes from the Robot machine?

**Comment by samcday** [comment]
Sorry, no - the block volumes cannot be attached to the bare metal machines. If you wanted to make hcloud block storage available to dedicated nodes you could consider deploying something like [Longhorn](https://longhorn.io/docs/1.1.2/) in your cluster.

**Comment by gris-gris** [comment]
Thanks for your answer, that thread can be closed now.
