### ISSUE TITLE
Links in the readme are not working (404)

### ISSUE THREAD

**Issue by exocode** [hetznercloud/csi-driver#24]
Links in the Readme are not working:

`See Enabling features and Enable privileged Pods in the Kubernetes CSI documentation.`

https://kubernetes-csi.github.io/docs/Setup.html#enabling-features
https://kubernetes-csi.github.io/docs/Setup.html#enable-privileged-pods

**Comment by exocode** [comment]
BTW: This one (also in the readme) is not working

https://kubernetes-csi.github.io/docs/Setup.html#enabling-csinodeinfo

**Comment by thcyron** [comment]
Fixed them in a2213d85282e8b3f6ed24f5d2ebcf3679007a74f.
