### ISSUE TITLE
Will this driver support attaching the volume to k8s node?

### ISSUE THREAD

**Issue by lucernae** [hetznercloud/csi-driver#255]
Hi, I'm sorry if this question sounds weird.

I actually want to have this use case described in this pinned issue: https://github.com/hetznercloud/csi-driver/issues/131

The reason why I need it is because I am using Hetzner volume as attached disk for a Longhorn instance, so I need the Hetzner Volume actually attached to a Node so that I can register it in Longhorn.

My options/questions are:
- Understanding what were the driver options this csi-driver currently supports to be passed in the PVC claim or PV
- Can we provision Block/Device mode?
- If we can only provision PVC in FS mode, how do we get the device name? The one usually available in /dev/disk-by-id
- Can we schedule the PV to only be mounted in a certain node (just one specific node)? I'm guessing this is possible since you have node affinity in the PV, but just to make sure, I want to ask it.

I know those are such an odd questions. But, if I can somehow get access to the device/device name I can automate the mount to the node.

**Comment by fhofherr** [comment]
Hi,

this sounds like you are trying to use the Hetzner CSI driver to provide storage for [Longhorn](https://github.com/longhorn/longhorn) which in itself is a CSI driver. I don't know if this is possible, but I believe you have easier options:

1. Don't use longhorn. The Hetzner CSI driver is capable of creating a volume for any persistent volume claims you define. Assuming you do not interfere with the CSI driver's access to the metadata server like in #131 you should be done. Of course this means that a new volume is created for each PVC.
2. Do not use the Hetzner CSI driver, but instead Longhorn. In this case you need to attach the Hetzner Cloud volumes upon server creation to the Servers that form the nodes of your cluster. Then you configure Longhorn to use the paths of the volumes. Also, a Hetzner Cloud volume can only be attached to a single server at any given time. Therefore, if you plan to replicate your data using Longhorn, you will need to attach a separate volume to each node.

The volumes themselfes can be found in `/dev/disk/by-id/scsi-SHC_Volume_<volume_id>` where `volume_id` is the ID of the volume as returned by the Hetzner Cloud API.

**Comment by janosmiko** [comment]
Hi @fhofherr 

If you choose the first case, how can you create more than 16 persistent volumes? AFAIK Hetzner instances can only handle 16 attachments at a time.

I guess the use-case here would be the following:
- attach some large persistent volumes using hcloud-csi driver
- pass these attached drives to longhorn
- create any PVs using longhorn storageclass

**Comment by fhofherr** [comment]
With respect to first case: the answer is unfortunately that you can't. 

I'd suggest to attach some large Hetzner Cloud Volumes to each node that is intended to provide storage and then use longhorn to create PVCs using the storage provided by those volumes. Not that you will need a separate Hetzner Volume for each cluster node you want to provide storage. You don't need the CSI driver to attach those volumes. In this case it would be easier to attach those volumes using a different automation. For example if you use terraform to create your cluster nodes you could also use that to create and attach the volumes.

**Comment by lucernae** [comment]
What I need is the device name attached to the kubelet (or node in this case).

> The volumes themselves can be found in /dev/disk/by-id/scsi-SHC_Volume_<volume_id> where volume_id is the ID of the volume as returned by the Hetzner Cloud API.

Yes, I need this one. Is this exposed in k8s API somehow? I can see that I can get the volume_id from the PV resource (volume handle field). But how am I sure that `/dev/disk/by-id/scsi-SHC_Volume_<volume_id>` is always the pattern for the block device attached to kubelet/node? Is it returned in k8s API somewhere?

> this sounds like you are trying to use the Hetzner CSI driver to provide storage for Longhorn which in itself is a CSI driver. I don't know if this is possible, but I believe you have easier options:

No worries, I was not planning to attach the storage to the node using CSI. What I want to do is to get whatever `/dev/disk` name created by PVC requests. My use case is that I use PVC with hcloud-volume storage class then attach it to available node (via other means). Then use the mounted path as Longhorn disk. These can be automated as long as I knew the `/dev/disk` name, and I was wondering if this information is available or managed by the driver, because obviously the driver need to have the block device accessible by kubelet so that kubelet can attach it to pod.

> For example if you use terraform to create your cluster nodes you could also use that to create and attach the volumes.

We want to skip terraform because we are using this in some kind of testing pipeline where instance is created and destroyed on the fly (not GitOps). So our flow is more or like what @janosmiko described above.

As I understand from the discussion:
- this CSI driver only handles FS mode not block device
- device pattern is: `/dev/disk/by-id/scsi-SHC_Volume_<volume_id>`. but not sure if it is always like this, can you confirm?
- I did my own experiment, it seems the PV node affinity does works. This is going to be useful for me.

**Comment by fhofherr** [comment]
> * device pattern is: `/dev/disk/by-id/scsi-SHC_Volume_<volume_id>`. but not sure if it is always like this, can you confirm?

The device name is assigned upon attaching the volume to the server. We control the udev rule that creates the device name and have no inclination of changing it. So I'd say it is pretty stable, although I can't give any stability guarantees for the far future.

> We want to skip terraform because we are using this in some kind of testing pipeline where instance is created and destroyed on the fly (not GitOps).

Whatever your flow is to create a server, I'd suggest you look into creating the volume and attaching it to the server there. That way you only need to take care of configuring Longhorn. So basically, replace the first bullet point from @janosmiko's description and do it outside of kubernetes.

**Comment by lucernae** [comment]
Thanks @fhofherr, it seems I have a good starting point if the device name is stable!
