### ISSUE TITLE
Idea: Move away from mount-utils

### ISSUE THREAD

**Issue by choffmeister** [hetznercloud/csi-driver#280]
After having worked on this driver I noticed, that the use of mount-utils library makes stuff kind of complicated to understand what is really happening. The library solves a lot of edge cases not relevant for the hcloud csi driver (mounting NFS mounts, different OSes and stuff). But all that is really needed is a simple `mount` and `umount` command. So I would suggest to drop the lib and instead just make the needed command calls directly.

What is the maintainers team opinion on that? Would that be something you would accept PRs for?

**Comment by samcday** [comment]
Hello @choffmeister yes this sounds great. I recently made a series of changes that excised a bunch of code from the node side of this driver, but I feel the endeavor is still incomplete. Simplifying the mount/unmount logic would be great.
