### ISSUE TITLE
Docker Hub registry pull rate limitation

### ISSUE THREAD

**Issue by schamane** [hetznercloud/csi-driver#295]
Hi,

i had this issue already few times, had to wait 6 hours to re-pull one of the hetzner images used for csi that are hosted on docker hub registry - docker.io

Maybe hetzner can provide own registry, or use other one, or provide way to install images with own docker.io credentials to not be affected by docker.io pull request ration limitations ?

Thanks

**Comment by LKaemmerling** [comment]
Hey @schamane,

you can easily change the deployment file to add the docker hub credentials (or any other image source). Just copy the file to your locale machine, make the changes and deploy it to your cluster :)

**Comment by schamane** [comment]
I know, that was not a problem ;D
Proper solution would be maybe use some other registry provider with brighter restrictions. Why Hetzner doesn't has own one?
But thanks, @LKaemmerling 

PS. If no there will be no other solution here, please close Issue...
