### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by holooloo** [hetznercloud/csi-driver#300]
Just installed a new fresh vanila K8S with Kubespray and got:
**panic: runtime error: invalid memory address or nil pointer dereference**

**Comment by LKaemmerling** [comment]
Hey @holooloo,

would it be possible for you to provide more information? The whole stack trace would be a good first step together with a few details about your setup.

**Comment by holooloo** [comment]
No need to fix, somehow it works
