### ISSUE TITLE
wrong secret name - must be "hcloud-csi" for master / 1.6.0

### ISSUE THREAD

**Issue by flypenguin** [hetznercloud/csi-driver#307]
i get an error "secret 'hcloud-csi' not found". sure, i created the secret with the name `hcloud`, as defined.

please change the secret creation docs to be `name: hcloud-csi`.

**Comment by LKaemmerling** [comment]
Hey @flypenguin,

the readme is correct, as it is already for the next version of the CSI driver that unifies the secret name with the cloud controller manager. However I changed the description in a way that should prevent further issues.
