### ISSUE TITLE
Upgrading from 1.6.0 to master: invalid: spec.fsGroupPolicy

### ISSUE THREAD

**Issue by vitobotta** [hetznercloud/csi-driver#308]
Hi! I upgraded from 1.6.0 to master to support newer versions of k8s and I get this:

```
The CSIDriver "csi.hetzner.cloud" is invalid: spec.fsGroupPolicy: Invalid value: "File": field is immutable
```

What can I do? Volumes seem to work though. Thanks!

**Comment by llama0815** [comment]
same here on Kubernetes v1.21.4

**Comment by apricote** [comment]
The field was added in preparation of the new v2 of the driver and is a breaking change. A migration guide will be published when the new version is actually released.

**Comment by apricote** [comment]
The migration guide for `v2.0.0` includes documentation on how to approach this issue during the upgrade: https://github.com/hetznercloud/csi-driver#from-v1-to-v2

If you still have issues with this, please feel free to reopen the issue or create a new one.
