### ISSUE TITLE
Pod failed to mount volume, had to manually add node label.

### ISSUE THREAD

**Issue by Troyhy** [hetznercloud/csi-driver#31]
I installed CSI driver and ran the test yaml.
Volume was created, but busybox could not mount it.
```
Warning	FailedScheduling 0/5 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 1 node(s) were unschedulable, 3 node(s) had volume node affinity conflict.
```
I had to manually add label ```csi.hetzner.cloud/location=hel1```, after witch  the test busybox was able to mount the volume.

Should these labels be automatically created by csi-driver?

**Comment by thcyron** [comment]
That label should have been created by the CSI driver itself.

Do you use the latest version and did you enable the necessary feature gates as described in the readme?

**Comment by Troyhy** [comment]
I'm running Rancher 2.2.0-rc6 and RKE created cluster. So most probably I don't have feature-gates on.
