### ISSUE TITLE
Publish new image that includes latest changes

### ISSUE THREAD

**Issue by hakman** [hetznercloud/csi-driver#310]
The last published image is version 1.6.0, from about 1 year ago.
Since then, there are quite a few [changes](https://github.com/hetznercloud/csi-driver/compare/v1.6.0...main), most notable being the security improvements and volume encryption (which is also documented in the [README](https://github.com/hetznercloud/csi-driver/blob/main/README.md) file.

PS: Would be nice to also upgrade the CSI Sidecar Containers.

**Comment by hakman** [comment]
@LKaemmerling @4ND3R50N Any thoughts about publishing new csi-driver images?

**Comment by LKaemmerling** [comment]
Hey @hakman,

we currently work on a lot of improvements on the CSI driver front, also we already had a lot of "breaking" changes in the main branch and we want to finish those changes before making a new v2.0 release. I expect to have more drive on the CSI driver in the next couple of weeks.

**Comment by hakman** [comment]
Thanks for the update @LKaemmerling. I agree about the breaking changes and appreciate the work you are doing. Looking forward to see v2.0.

**Comment by EternalDeiwos** [comment]
Any ETA on a release? I'm currently playing with LUKS encrypted volumes (#279) from `main` but would be nice to really start leaning on them without the threat of something being broken.

**Comment by apricote** [comment]
We plan on releasing v2.0.0 at the beginning of next week, there is one internal dependency remaining that we need to tackle, so the release may be delayed.

**Comment by apricote** [comment]
`v2.0.0` is released: https://github.com/hetznercloud/csi-driver/releases/tag/v2.0.0

**Comment by hakman** [comment]
Thanks @apricote!
