### ISSUE TITLE
Kubernetes 1.25 support?

### ISSUE THREAD

**Issue by xrstf** [hetznercloud/csi-driver#315]
The compat matrix in the README does not yet mention support for Kubernetes 1.25. Can we safely install v1.6.0 into Kubernetes 1.25 clusters?

**Comment by cristianrat** [comment]
I would also like to know that :)

**Comment by rmja** [comment]
I guess that I am brave, but I am running the csi-driver 1.6.0 on a kubernetes 1.25 cluster without any issues.

**Comment by cristianrat** [comment]
> I guess that I am brave, but I am running the csi-driver 1.6.0 on a kubernetes 1.25 cluster without any issues.

Truly the tip of the spear!
Thank you for testing and sharing the results :)

**Comment by apricote** [comment]
We now test our `main` branch against Kubernetes v1.25. This should be released as v2.0.0 within the week.

As you have discovered, v1.6.0 _should_ work with Kubernetes v1.25, as we do not use any removed APIs and also the CSI support from Kubernetes did not change, but this has not explicitly been tested by us.

If you want to be sure, you can run the official kubernetes e2e tests for CSI Drivers for Kubernetes v1.25 by following the guide in our README: https://github.com/hetznercloud/csi-driver#e2e-tests
