### ISSUE TITLE
feat: Support SINGLE_NODE_MULTI_WRITER capability

### ISSUE THREAD

**Issue by apricote** [hetznercloud/csi-driver#327]
CSI Spec v1.5.0 introduced a new Capability `SINGLE_NODE_MULTI_WRITER`, which specializes the `SINGLE_NODE_WRITER` volume access mode into the "sub"-access modes `SINGLE_NODE_SINGLE_WRITER` and `SINGLE_NODE_MULTI_WRITER`.

This was added because the existing spec was conflicting. We currently behave like `SINGLE_NODE_MULTI_WRITER`, so we should just use that in the code.

This requires upgrading all our sidecar containers.

We can also enable the Kubernetes E2E tests flag `Feature:SELinuxMountReadWriteOncePod` once we have implemented this.

**Comment by lukasmetzner** [comment]
Controller service is not yet responding with the SINGLE_NODE_MULTI_WRITER capability. This needs to be added.

**Comment by lukasmetzner** [comment]
Done with PR #732
