### ISSUE TITLE
FailedAttachVolume, volume is already attached to a server, please detach it first

### ISSUE THREAD

**Issue by akhfa** [hetznercloud/csi-driver#34]
Hi
Thanks for this CSI driver, most of the time this CSI driver works great
I use kubespray with kubernetes 1.13.5

But I have some problems
When I rolling-upgrade my kubernetes, some of the pvc failed to be attached to new server because it still attached to the old server
```
  Warning  FailedAttachVolume  24m (x2 over 24m)   attachdetach-controller      AttachVolume.Attach failed for volume "pvc-9b8b9ad0-50b3-11e9-b9f7-9600001dedca" : rpc error: code = Internal desc = failed to publish volume: cannot perform operation because server is locked (locked)
  Warning  FailedAttachVolume  22s (x18 over 24m)  attachdetach-controller      AttachVolume.Attach failed for volume "pvc-9b8b9ad0-50b3-11e9-b9f7-9600001dedca" : rpc error: code = Internal desc = failed to publish volume: volume is already attached to a server, please detach it first (service_error)
  Warning  FailedMount         11s (x11 over 22m)  kubelet, node1  Unable to mount volumes for pod "prometheus-server-0_monitoring(c070914c-66e0-11e9-a87d-9600001dedca)": timeout expired waiting for volumes to attach or mount for pod "monitoring"/"prometheus-server-0". list of unmounted volumes=[storage-volume]. list of unattached volumes=[storage-volume config-volume prometheus-server-token-lhlf6]
```
I go to the VM where the volume attached, and see that it already in unmounted state, so
I manually detach related pvc from cloud console (volume page), and then delete related pods so it can quickly be rescheduled. After that, related volume can be attached to new server automatically (but sometimes need to be manually attached too)

Is it expected to be happened? I think there is something that should always check the volume state, and detach it if required

**Comment by Troyhy** [comment]
This is expected, as volumes only support  ReadWriteOnce. Rolling update is not possible with these volumes.
> ReadWriteOnce – the volume can be mounted as read-write by a single node

**Comment by akhfa** [comment]
Hi
I don't think I have the same issue when using AWS with EBS PVC attached. I use k8s version < 1.13 tough, so maybe different process when detaching PVC.

Anyway, when we drain a node, a pod will be terminated, and then spawned into another node, isn't it? 

Can we just "unattached" related PVC from the old node after the old pod terminated? 

Or can we just check when we get error attaching PVC to new node, we remove the volume from old node because we are sure that the pod already scheduled to new node?

**Comment by Troyhy** [comment]
> Anyway, when we drain a node, a pod will be terminated, and then spawned into another node, isn't it?
Yes, I belive thats correct.

> Can we just "unattached" related PVC from the old node after the old pod terminated?
With Hetzned CSI volumes driver takes care of *unattaching* and *attaching* volume to node where new pod is scheduled.

Problem with *RollingUpdate* is that it tries to schedule pod before old pod is terminated. So I used ```
 strategy:
    type: Recreate
```
in similar situations.

**Comment by akhfa** [comment]
Hi,

I think I got the idea. Actually I know about `Recreate` but I never try it for this issue. I think it should be ok.

I will close the issue for now and will reopen this issue later if I have similar issue.

Thank you!
