### ISSUE TITLE
Unable to Authenticate

### ISSUE THREAD

**Issue by iburrows** [hetznercloud/csi-driver#35]
Hi I have followed the README and used the most recent release but hcloud-csi-controller and hcloud-csi-node are both in CrashLoopBackOff and I can't figure out what is wrong from the logs. I have the correct api key in the secret. Thanks for any help. I have attached the logs from hcloud-csi-controller and hcloud-csi-node.

The only thing that makes sense is the unable to authenticate error? I used this guide to setup the cluster: https://vitux.com/install-and-deploy-kubernetes-on-ubuntu/. Am I maybe missing something which is not allowing correct authentication?

[csi-attacher.txt](https://github.com/hetznercloud/csi-driver/files/3159573/csi-attacher.txt)

[csi-cluster-driver-registrar.txt](https://github.com/hetznercloud/csi-driver/files/3159575/csi-cluster-driver-registrar.txt)

[csi-provisioner.txt](https://github.com/hetznercloud/csi-driver/files/3159576/csi-provisioner.txt)

[hcloud-csi-driver.txt](https://github.com/hetznercloud/csi-driver/files/3159577/hcloud-csi-driver.txt)

**Comment by thcyron** [comment]
Please double-check the token you specified in the secret. Make sure it’s 64 characters. Check it’s valid by invoking:

```
curl -H "Authorization: Bearer ao...D7" https://api.hetzner.cloud/v1/locations
```

**Comment by iburrows** [comment]
Thanks, the incorrect token was the issue.
