### ISSUE TITLE
feat(deploy): Use registry.k8s.io for kubernetes-csi sidecars

### ISSUE THREAD

**Issue by apricote** [hetznercloud/csi-driver#368]
We should switch the registry for the kubernetes-csi sidecar container from using `k8s.gcr.io` to `registry.k8s.io`: https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/

(previously requested in #339)

**Comment by mysticaltech** [comment]
More context here https://github.com/kubernetes/registry.k8s.io

![ksnip_20230126-023442](https://user-images.githubusercontent.com/518555/214736220-2e10be39-75af-450c-ab5f-19a9ba1de14a.png)
