### ISSUE TITLE
Docker Swarm support: Remove mock staging/unstaging once possible

### ISSUE THREAD

**Issue by s4ke** [hetznercloud/csi-driver#382]
In the original PR #376 we added a workaround where we added mock staging/unstaging support that will not be needed anymore once https://github.com/moby/swarmkit/pull/3116 is merged.

This issue is here to track this TODO.

**Comment by s4ke** [comment]
This should work without by

**Comment by apricote** [comment]
Hey @s4ke, could you implement this?

**Comment by s4ke** [comment]
Yes I can, but I have to see where it fits my schedule. Any hard deadline for when you want this in?

**Comment by apricote** [comment]
Wonderful :) No deadline, would just love to see this done before the stale bot tries to close it again (~3 months)

**Comment by s4ke** [comment]
May I ask you to remind me if this is still not done in let's say, 1 month?

**Comment by apricote** [comment]
Well, I forgot about it :D @s4ke ping.

**Comment by s4ke** [comment]
Same here. If anyone else wants to take this, this is probably also a good first issue since it is just about removing operations and testing once against a Swarm.

**Comment by apricote** [comment]
If anyone wants to send a PR:

- Revert commit https://github.com/hetznercloud/csi-driver/pull/376/commits/619fa5c3996e17e84b09deca0c956229e5554c77
- Test against a current version of Docker Swarm
