### ISSUE TITLE
Node fails to pull images

### ISSUE THREAD

**Issue by EnricoMessall** [hetznercloud/csi-driver#384]
With https://github.com/vitobotta/hetzner-k3s i try to create a cluster with some workers. With two workers everything is working good but when i have 3 or more workers mostly one of the worker fails on the hcloud-csi yaml fetching from the Google Cloud Registry with 403. 

Might it be when fetching those images to fast the image pulls get blocked?

If i could see that right, fetching from registry.k8s.io the cloud server is sending these requests through the reverse dns for IPv4. Could be a case that google blocks those requests from the Hetzner Proxy if they are to many requests because Google Cloud thinks it is one domain and limits the requests?

(Addition: Since today also pulling fails often with only one master container)

**Comment by apricote** [comment]
I think this might be the same issue as #373. We are aware of sporadic issues where IP addresses are blocked by Google & AWS, could you send me all affected IPs to my email at `julian.toelle <at> hetzner-cloud.de` or open a [support ticket](https://console.hetzner.cloud/support)?

I have not yet heard of any (significant) rate limiting happening with that registry. By default your servers should each communicate through their own Primary IP address (or Floating IP if assigned).

**Comment by psavva** [comment]
It seems that google has changed repository URLs

I've confirmed that replacing `k8s.gcr.io` with `registry.k8s.io` for all images (6 in total) will fix the issue.

I will open a PR for this

**Comment by EnricoMessall** [comment]
@psavva Thats already an update for the next release. When you look into the current master branch under deploy hcloud-csi yaml is already updated see: https://raw.githubusercontent.com/hetznercloud/csi-driver/master/deploy/kubernetes/hcloud-csi.yml

**Comment by apricote** [comment]
> You can just take the link to the file in deploy/kubernetes for your Kubernetes Cluster with the new registry.k8s.io repository urls. 

Just note that this uses the `latest` images and we do not provide additional support for this.

**Comment by fatelgit** [comment]
I can confirm this issue as well. Sidefact: We are having huge problem with some of our nodes when connecting to mailgun api as well :(
Back to topic: A quick fix for me was replacing the daemonset image url with docker hub. 

longhornio/csi-node-driver-registrar:v2.7.0
longhornio/livenessprobe:v2.9.0
