### ISSUE TITLE
Add encryption support

### ISSUE THREAD

**Issue by loxal** [hetznercloud/csi-driver#40]
Currently I am enabling encryption as simple as 

>       "echo -n \"${local.admin_password}\" | cryptsetup luksFormat /dev/disk/by-id/scsi-0HC_Volume_${hcloud_volume.al-data-node.id}",
>       "echo -n \"${local.admin_password}\" | cryptsetup luksOpen /dev/disk/by-id/scsi-0HC_Volume_${hcloud_volume.al-data-node.id} encrypted-contract-analyzer-storage",
>       "mkfs.ext4 /dev/mapper/encrypted-contract-analyzer-storage",
>       "mount -o discard,defaults /dev/mapper/encrypted-contract-analyzer-storage /mnt/al-data",

via Terraform. It would be great if you could provide an option to enable encryption.

**Comment by thcyron** [comment]
I don’t think encryption is in the scope of a CSI driver. Or are you aware of any driver that actually has encryption support?

**Comment by loxal** [comment]
I do not want to debate the scope. I just want to propose a feature and this repository was my best guess to reach appropriate stakeholders. I am absolutely not into debating driver scope and other tech. details with an employee of Hetzner. I just ask for a feature as a customer. I am pretty sure you can figure out how to provide this feature within K8s and simplify your customers lives so they can buy more of your stuff.

**Comment by gigo1980** [comment]
I think what @loxal would request is https://en.wikipedia.org/wiki/Bring_your_own_encryption

Azure is doing this in a parameter of the storage class: https://docs.microsoft.com/de-de/azure/aks/azure-disk-customer-managed-keys#encrypt-your-aks-cluster-data-disk

So, in my opinion, this could be a CNI topic and for some customers mandatory.

**Comment by harshitmahapatra** [comment]
We are using hetzner volumes in our company and this feature would be very helpful.
