### ISSUE TITLE
Attaching fails because volume is wrongfully assumed to be attached elsewhere

### ISSUE THREAD

**Issue by alvaroaleman** [hetznercloud/csi-driver#41]
So, the symptoms look like this, a pod doesn't start because:

```
alvaro@t470s-[2019-06-20-22:50]:[master]
[...]
  Warning  FailedAttachVolume  3s    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-7ff22820-9333-11e9-b435-96000019d538" : rpc error: code = Internal desc = failed to publish volume: volume is already attached to a server, please detach it first (service_error)
```

I assumed this is because for some reason the controller does something wrong when detaching, but:

```
alvaro@t470s-[2019-06-20-22:50]:[master]
$ hcloud volume detach pvc-7ff22820-9333-11e9-b435-96000019d538
hcloud: volume not attached to a server (service_error)
```

I then assumed that maybe there is an inconsistency in the API which is why the attaching doesn't work, but:

```
alvaro@t470s-[2019-06-20-22:52]:[master]
$ hcloud volume attach --server [redacted]-5446d9cdc8-rpkfk pvc-7ff22820-9333-11e9-b435-96000019d538 
   1s [====================================================================] 100%
Volume 2758011 attached to server [redacted]-5446d9cdc8-rpkfk
````

So it seems to me the controller thinks for some reason the volume is attached when it is actually not, tries to detach it, which fails because it isn't attached and the whole thing gets stuck.

**Comment by costela** [comment]
AFAIK the `attachdetach-controller` is only responsible for creating `VolumeAttachment` objects, which are in turn picked up by the `csi-external-attacher` sidecar and forwarded to the driver. So the error seems to be hapenning before we even get to the driver.
What does `kubectl get pvc YOURPVC -ojsonpath='{ .status.phase }'` say?
Or maybe `kubectl get volumeattachment`?

**Comment by LKaemmerling** [comment]
Since this issue is quite old, could you please try it again with the latest version? If the problem continues to exist for you, please reopen the issue.
