### ISSUE TITLE
No Images available

### ISSUE THREAD

**Issue by derfabianpeter** [hetznercloud/csi-driver#416]
Hey there,

just tried to install v2.3.2 but the images referenced in the manifests seem to not be available: `docker pull hetznercloud/hcloud-csi-driver:2.3.2`

```
Error response from daemon: manifest for hetznercloud/hcloud-csi-driver:2.3.2 not found: manifest unknown: manifest unknown
```

Anything I'm doing wrong here?

**Comment by apricote** [comment]
Image is now at `hetznercloud/hcloud-csi-driver:v2.3.2`:

```shell
➜ docker pull hetznercloud/hcloud-csi-driver:v2.3.2
v2.3.2: Pulling from hetznercloud/hcloud-csi-driver
0ce1dd7918a4: Pull complete
71ddd8923bea: Pull complete
111eee752211: Pull complete
ba1e76eba4ea: Pull complete
Digest: sha256:b7ed90d5fab2c3fc63bf3ecb2193d3d18c1ec368c7ad98b2dbf633f0ada6afba
Status: Downloaded newer image for hetznercloud/hcloud-csi-driver:v2.3.2
docker.io/hetznercloud/hcloud-csi-driver:v2.3.2
```

Going to fix the README imminently

**Comment by derfabianpeter** [comment]
Yeah totally my bad. I used the manifests linked in the Kubernetes docs, BUT: I'm not using the manifests directly but feed them to a bigger templating framework in our platform. Of course I missed the new `v` prefix for the driver image when doing my Copy-Pasta. Sorry for the unneeded work I caused you.
