### ISSUE TITLE
Still connecting to unix://... only on one node (NAT, no public interface)

### ISSUE THREAD

**Issue by ibot3** [hetznercloud/csi-driver#419]
I am currently using v2.3.2 of the CSI driver.

I added an arm64 cloud server to my cluster and the CSI-Driver doesn't want to run on this node.

There are only two differences between this one node and all others:
- k8s 1.25 (all others 1.24)
- arm64

Furthermore, all my k8s nodes don't have an public interface, all traffic is routed through an additional cloud server via a private network. This doesn't seem to be a problem for all other nodes.

The `hcloud-csi-driver` only has this output: (with debug mode)
```
level=debug ts=2023-06-06T19:37:22.007073134Z component=metrics-service msg="registering metrics with registry"
level=debug ts=2023-06-06T19:37:22.007203935Z component=metrics-service msg="registered metrics"
```

Anyone has an idea what the problem is with this node?

The `hcloud-csi-driver` is able to reach the hcloud API (at least ping is working). The corresponding node is able to curl the API.

**Comment by ibot3** [comment]
Update:
k8s 1.25 doesn't seem to be the problem, I upgraded an other node and the CSI driver still works.

**Comment by apricote** [comment]
Hey @ibot3, is the issue with the Deployment `hcloud-csi-controller` or the DaemonSet `hcloud-csi-node`?

**Comment by ibot3** [comment]
> Hey @ibot3, is the issue with the Deployment `hcloud-csi-controller` or the DaemonSet `hcloud-csi-node`?

It's a problem with the DaemonSet, the pod of the DaemonSet running on that specific node.

**Comment by ibot3** [comment]
Was a problem with the DNS of the node.
On the host, the external DNS server was used before the cluster DNS server.
