### ISSUE TITLE
fix: btrfs volumes can not be formatted

### ISSUE THREAD

**Issue by apricote** [hetznercloud/csi-driver#421]
We support btrfs volumes since #200, but it looks like the formatting was not added in #279 when we changed the way volumes are formatted.

We need to add a case for formatting btrfs volumes [here](https://github.com/hetznercloud/csi-driver/blame/3490dec787cb8af51d85b8b49180d3f5a9144571/volumes/mount.go#L202-L218) and to the [e2e test configuration](https://github.com/hetznercloud/csi-driver/blob/3490dec787cb8af51d85b8b49180d3f5a9144571/test/e2e/kubernetes/testdriver-1.23.yaml#L28-L30) to make sure that it actually works and we do not accidentally break it in the future.

_Originally posted by @felixscheinost in https://github.com/hetznercloud/csi-driver/issues/200#issuecomment-1594188429_

**Comment by felixscheinost** [comment]
Thank you for opening the issue! I'm curious to see what the e2e tests say. Could be that this is an easy fix, right?

**Comment by apricote** [comment]
Yea, `btrs-progs` are already installed, so adding it back in should be ~3 lines and a quick sanity check that it actually works.

**Comment by apricote** [comment]
Fixed in #424
