### ISSUE TITLE
ReadWriteMany / RWX support

### ISSUE THREAD

**Issue by DrZoidberg09** [hetznercloud/csi-driver#423]
Hi there,

I know the CSI-Driver currently only supports RWO. However, as it is Ceph based backend - I think?!? - it should be also able to deal with RWX.

Is there any plan if and when to add RWX capabilities to the CSI-Driver as well?

This would be definitely a highly interesting feature for Hetzner.

Thanks!

**Comment by mraerino** [comment]
the main limitation is that a volume can only be attached to a single node right now, so hetzner would first need to add a feature that changes that behaviour in general, before anything can be done in the CSI

**Comment by aleksasiriski** [comment]
As a workaround you can use openebs-nfs-provisioner with hcloud-volumes as backend.

**Comment by BrutalBirdie** [comment]
This would be awesome ❤️

**Comment by apricote** [comment]
Hey all,

@mraerino is right, this is not supported by the current Hetzner Cloud Volumes product. I have added your feature request to our internal feedback tool to take into consideration for future development.

We only keep issues open that are possible to implement within the realm of the project, so I am going to close this issue.

---

To explain why this does not work:

- The Volumes are block storage which are exposed as a hardware device to the server
- The file system on the VM expects that it is the only one writing to the Block Storage Device
- For RWX you need to have some networked file system, like NFS, which can handle multiple users

**Comment by devantler** [comment]
@apricote have this been reconsidered internally? Can you share anything on whether this is planned in the foreseeable future? :-)

**Comment by lukasmetzner** [comment]
@devantler Hey, unfortunately this won't be implemented anytime soon.

**Comment by devantler** [comment]
@lukasmetzner any change on the stance for this? It would really be nice IMO.

**Comment by lukasmetzner** [comment]
@devantler Unfortunately there is no news :/

**Comment by mrhein** [comment]
https://github.com/mrhein/hcloud-csi-rwx
