### ISSUE TITLE
Missing support for arm64/aarch64 cloud servers on Docker Swarm

### ISSUE THREAD

**Issue by modrink** [hetznercloud/csi-driver#428]
Migrated from #427.

From [comment made by @apricote](https://github.com/hetznercloud/csi-driver/issues/427#issuecomment-1614643705) it seems that the plugin is currently only built for `amd64` architecture cloud servers.

Seeing as Hetzner has recently started offering `arm64` cloud servers, it would be nice to have `csi-driver` support for it.

**Comment by apricote** [comment]
We do not officially support the docker-swarm plugin. If anyone wants to contribute the necessary changes, I would be glad to review and merge them :)

The code for the docker-swarm plugin can be found in [deploy/docker-swarm/pkg](https://github.com/hetznercloud/csi-driver/tree/main/deploy/docker-swarm/pkg)

**Comment by s4ke** [comment]
As far as I know, Docker Swarm plugins can't be built as multiarch. We would need a suffix for the tag to support other architectures.

That being said, adding support should be straightforward.

**Comment by s4ke** [comment]
@apricote just as a general thing - feel free to ping me about issues with the Swarm packaging, happy to help.

In other notes, we can just establish a naming scheme `<tag>-swarm-<arch>` and to not break compatibility with existing solutions leave  `<tag>-swarm` as an alias for amd64?

**Comment by apricote** [comment]
Thanks to @s4ke there are now arm64 images available (on the `latest` tag, will be included in next release): https://hub.docker.com/layers/hetznercloud/hcloud-csi-driver/latest-swarm-arm64/images/sha256-e692705ec8517e4a87ca600edf8e84bc8524da9817eb79ed266a8384c7945ff7?context=explore
