### ISSUE TITLE
[rancher/k3s only] attacher.Attach failed: volumeattachments.storage.k8s.io is forbidden

### ISSUE THREAD

**Issue by ilyasotkov** [hetznercloud/csi-driver#46]
This was first reported by @costela in https://github.com/hetznercloud/csi-driver/issues/42#issuecomment-515753706.

```
E0727 14:03:55.220699    2205 csi_attacher.go:93] kubernetes.io/csi: attacher.Attach failed: volumeattachments.storage.k8s.io is forbidden: User "system:node:master1" cannot create resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: can only get individual resources of this type
```

> I suspect this might be related, because the call to create the VolumeAttachment happens from the master node, instead of the worker node where the pod is scheduled, so the admission is denied by the node authorizer (AFAICT, it only allows create requests for VolumeAttachment to be made by the Node actually running the pod using the volume).

I'm consistently getting this issue regardless of which node the pod that needs a volume attached is scheduled on.

The core of this issue seems to be that the attachdetach-controller (source https://github.com/kubernetes/kubernetes/tree/release-1.14/pkg/controller/volume/attachdetach), which should be using its own service account called `system:controller:attachdetach-controller`, is apparently instead using `system:node:<NODE_NAME>` service account, for unknown to me reasons.

I'm getting this on a [rancher/k3s](https://github.com/rancher/k3s) distribution of Kubernetes (version 1.14.5), and I'm not sure whether the issue is caused by this csi-driver or not, but since @costela already reported this earlier, I'm creating an issue here.

**Comment by ilyasotkov** [comment]
Here's the stack trace

```
 E0810 21:31:58.628682    4032 csi_attacher.go:93] kubernetes.io/csi: attacher.Attach failed: volumeattachments.storage.k8s.io is forbidden: User "system:node:master" cannot create resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: can only get individual resources of this type
 goroutine 91374 [running]:
 github.com/rancher/k3s/vendor/k8s.io/klog.stacks(0x6082c00, 0x5d92d26, 0xf, 0x5d)
         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:828 +0xb1
 github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).output(0x6082c40, 0xc000000002, 0xc001b54000, 0x5d92d26, 0xf, 0x5d, 0x0)
         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:737 +0x57b
 github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).printDepth(0x6082c40, 0x2, 0x1, 0xc00b46fd40, 0x1, 0x1)
         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:669 +0x12b
 github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).print(...)
         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:660
 github.com/rancher/k3s/vendor/k8s.io/klog.Error(...)
         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:1164
 github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/csi.(*csiAttacher).Attach(0xc004902ff0, 0xc002391960, 0xc00466bf20, 0x6, 0x356f017, 0xc001e96000, 0x17c, 0x1000)
         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher.go:93 +0x957
 github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationGenerator).GenerateAttachVolumeFunc.func2(0x8, 0x3568b00, 0xc002a97b10, 0xc008306e70)
         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go:346 +0x9b
 github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run.func1(0xc001b03780, 0xc008306e70, 0x2b, 0x0, 0x0, 0xc0070e7c00, 0xc0030a57c0, 0xc0070e7c40, 0x38, 0x40, ...)
         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:143 +0x146
 created by github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run
         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:130 +0x2ce
```

**Comment by DracoBlue** [comment]
I am running into the very same issue when using this csi driver with k3s on hetzner cloud.

To reproduce the error I had to replace all ocurrences of `/var/lib/kubelet` in https://raw.githubusercontent.com/hetznercloud/csi-driver/master/deploy/kubernetes/hcloud-csi.yml with `/var/lib/rancher/k3s/agent/kubelet` because otherwise the volume reported:

```
default-scheduler  pv "pvc-1018fde8-bb50-11e9-b677-96000029eacb" node affinity doesn't match node "k3s-test": No matching NodeSelectorTerms
```

**Comment by costela** [comment]
@ilyasotkov funny you should create this issue. I've been investigating this off and on for the last couple of weeks, whenever I could find the time, and was wondering where to report it.

However, if my latest understanding is correct, I think this may be more of a k3s problem than a hcloud-csi problem. AFAICT, the driver doesn't have any influence on how the `attachdetach-controller` is authenticated.
My initial suspicion that it might be related to missing topology information was also debunked:
- k3s runs with `volumes.kubernetes.io/controller-managed-attach-detach: "true"`, so it's *expected* that the call should happen on the master as opposed to the kubelet.
- if it were a `NodeRestriction` issue, the actual error would be similar to the one linked by @DracoBlue (i.e.: "no relationship found between node X and this object").

Also, all information that the `attachdetach-controller` should need to create the `VolumeAttachment` seems correct. For instance, the pod is running on the same node as the PVC:
```
$ kubectl get pods my-csi-app -owide
NAME         READY   STATUS              RESTARTS   AGE     IP       NODE      NOMINATED NODE   READINESS GATES
my-csi-app   0/1     ContainerCreating   0          4m44s   <none>   worker1   <none>           <none>
```
and 
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi.hetzner.cloud
    volume.kubernetes.io/selected-node: worker1
  creationTimestamp: "2019-08-11T10:32:17Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: csi-pvc
  namespace: default
  resourceVersion: "251566"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/csi-pvc
  uid: XXXXXXXX-YYYY-ZZZZ-XXXX-YYYYYYYYYYYY
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
  volumeMode: Filesystem
  volumeName: pvc-XXXXXXXX-YYYY-ZZZZ-XXXX-YYYYYYYYYYYY
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
```

I'll keep looking on the k3s side, but I'd happily be proven wrong if someone actually finds the root issue, though! :)

**Comment by DracoBlue** [comment]
I tried with azures hostpath from https://github.com/Azure/kubernetes-volume-drivers/tree/master/csi/hostpath and retrieved the same message on k3s:

```
AttachVolume.Attach failed for volume "kubernetes-dynamic-pv-42256afbbc7411e9" : volumeattachments.storage.k8s.io is forbidden: User "system:node:k3s-test" cannot create resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: can only get individual resources of this type
Unable to mount volumes for pod "my-csi-app_default(3ac675b9-bc74-11e9-a41e-96000029eacb)": timeout expired waiting for volumes to attach or mount for pod "default"/"my-csi-app". list of unmounted volumes=[my-csi-volume]. list of unattached volumes=[my-csi-volume default-token-8d8kh]
```

Thus I am pretty sure @costela's idea, that k3s is doing something wrong here, will be right :(.

> AFAICT, the driver doesn't have any influence on how the attachdetach-controller is authenticated.

is there any way to retrieve (from a running k3s cluster) how it's authenticated by k3s?

**Comment by costela** [comment]
There seems to be enough evidence (another anecdotal report [here](https://forums.rancher.com/t/longhorn-on-k3s-pv-attach-error/14920)), that this isn't a driver issue.
Maybe we should move this discussion to the k3s issue tracker?

**Comment by vitobotta** [comment]
Hi, just ran into this issue. I was hoping I could use K3s because of the low resources usage :( So there is no workaround for now?

**Comment by ilyasotkov** [comment]
@costela Yep, I can also confirm the issue is specific to k3s, tried it with a [kubespray](https://github.com/kubernetes-sigs/kubespray) (Kubernetes 1.14.3) cluster, volumes create and attach just fine.

Created an issue in the k3s issue tracker: https://github.com/rancher/k3s/issues/732

**Comment by vitobotta** [comment]
I've played with authorization and seem to have found a workaround, I have updated the other ticked that @ilyasotkov opened in k3s.

**Comment by grumps** [comment]
I'm also seeing this issue with my the Digital Ocean CSI driver. I actually had it all working then destroyed my instance and started over again for automation and now it doesn't work. Based on the releases page I believe I was using 0.7.0. So it must of broken in the 0.8.0 release.

**Comment by ilyasotkov** [comment]
https://github.com/rancher/k3s/issues/732#issuecomment-533896909
