### ISSUE TITLE
OCI Error on ARM64 in Kubernetes

### ISSUE THREAD

**Issue by Spyros-Amvrakidis** [hetznercloud/csi-driver#463]
Hi, today i try to create a K3S cluster with just one node.
The node have 3 Network adapters

OS Ubuntu 22 ARM64

- VPN Adapter IPv4 100.90.0.63
- Internal Adapter IPv4 10.0.100.1
- External IPv4 IPv6

This is the K3S setup command i used: 
`curl -sfL https://get.k3s.io | sh -s - server \
  --token=MY_KEY \
  --tls-san LB_IP \
  --disable traefik \
  --disable local-storage \
  --disable metrics-server \
  --cluster-init \
  --datastore-endpoint="external mariadb"`
 I try to install the CSI Driver version 1.6.0  and all the time i take this Error
`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/hcloud-csi-driver-controller": stat /bin/hcloud-csi-driver-controller: no such file or directory: unknown`
I tried without external datastore with embeded etcd, i tried to rebuild the whole vm and i tried to remove all the adaptors expecte the public one. I check the VM doesnt haved the runc i installed and again nothing.

**Comment by apricote** [comment]
Hey @Spyros-Amvrakidis,

support for arm instances was only added in `v2.3.0`. Please try to install your cluster with the [latest version](https://github.com/hetznercloud/csi-driver/releases/latest) of hcloud csi-driver:
