### ISSUE TITLE
[Q] Still connecting to unix:///run/csi/socket

### ISSUE THREAD

**Issue by wmtbuddhika** [hetznercloud/csi-driver#465]
### Cluster:
```
controlplane     Ubuntu 22.04.2 LTS    Public network
workernode1    Ubuntu 22.04.2 LTS    Public network
```

### CSI Driver:
All the steps are followed mentioned here: https://github.com/hetznercloud/csi-driver/blob/main/docs/kubernetes/README.md#getting-started

`kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.3.2/deploy/kubernetes/hcloud-csi.yml
`
```
storageclass.storage.k8s.io/hcloud-volumes created
serviceaccount/hcloud-csi-controller created
clusterrole.rbac.authorization.k8s.io/hcloud-csi-controller created
clusterrolebinding.rbac.authorization.k8s.io/hcloud-csi-controller created
service/hcloud-csi-controller-metrics created
service/hcloud-csi-node-metrics created
deployment.apps/hcloud-csi-controller created
daemonset.apps/hcloud-csi-node created
csidriver.storage.k8s.io/csi.hetzner.cloud created
```

But the following pods failed to start.
```
hcloud-csi-controller     CrashLoopBackOff
hcloud-csi-node             CrashLoopBackOff
```

```
k logs -n kube-system hcloud-csi-controller-76b94f8979-r255g 
Defaulted container "csi-attacher" out of: csi-attacher, csi-resizer, csi-provisioner, hcloud-csi-driver, liveness-probe
I0720 13:26:24.701875       1 main.go:94] Version: v4.1.0
W0720 13:26:34.704235       1 connection.go:173] Still connecting to unix:///run/csi/socket
W0720 13:26:44.704749       1 connection.go:173] Still connecting to unix:///run/csi/socket
W0720 13:26:54.704400       1 connection.go:173] Still connecting to unix:///run/csi/socket
```

```
k logs -n kube-system hcloud-csi-node-mkrpv                 
Defaulted container "csi-node-driver-registrar" out of: csi-node-driver-registrar, hcloud-csi-driver, liveness-probe
I0720 13:26:24.983348       1 main.go:167] Version: v2.7.0
I0720 13:26:24.983419       1 main.go:168] Running node-driver-registrar in mode=registration
W0720 13:26:34.984823       1 connection.go:173] Still connecting to unix:///run/csi/socket
W0720 13:26:44.984894       1 connection.go:173] Still connecting to unix:///run/csi/socket
W0720 13:26:54.984596       1 connection.go:173] Still connecting to unix:///run/csi/socket
```

And the test pod is in the Pending stage, here are the Events of the pod,
```
Events:
  Type     Reason            Age                     From               Message
  ----     ------            ----                    ----               -------
  Warning  FailedScheduling  25m (x4 over 4h14m)     default-scheduler  0/2 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..
  Warning  FailedScheduling  5m19s (x28 over 4h54m)  default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: timed out waiting for the condition
```

And here is the PVC,
k get pvc
```
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS     AGE
csi-pvc   Pending                                      hcloud-volumes   5h7m
```

What did I miss or are any prerequisites that I need to have?

**Comment by apricote** [comment]
Hey @wmtbuddhika,

in previous iterations of this symptom (#139, #347, #247) it was usually some networking issue that blocked access to the [metadata service](https://docs.hetzner.cloud/#server-metadata)(for hcloud-csi-node & hcloud-csi-controller) or the [API](https://docs.hetzner.cloud/#getting-started) (for hcloud-csi-controller).

Can you try accessing both services from inside the csi pods?

I have been meaning to look into this in more depth and figure out why we never get any logs from the actual csi-driver container.

**Comment by wmtbuddhika** [comment]
Hi @apricote,
Thank you for the help.

I'm sorry, hence the csi pods are not in the running state, I couldn’t check whether they can be accessed both services from inside the pods. (please mention if there is any other way)

By the way, I can access both services from the nodes.

One mismatch I noticed is the hostname, (as discussed in #139)

```
curl http://169.254.169.254/hetzner/v1/metadata/hostname
ubuntu-16gb-hel1-1
```

But the node name is: `workernode1`

And,
```
curl -H "Authorization: Bearer giVbmYIwDaZ...."  https://api.hetzner.cloud/v1/servers
{
  "servers": [
    {
      "name": "workernode1",
      "status": "running",
....
```

Your help is highly appreciated.

**Comment by apricote** [comment]
The hostname should not matter, we try a lookup by Kubernetes Node name, but if that fails it should fall back to the Metadata Service.

Access to the API is required for the controller, otherwise we can not create and mount volumes.

**Comment by apricote** [comment]
The hostname should not matter, we try a lookup by Kubernetes Node name, but if that fails it should fall back to the Metadata Service.

Access to the API is required for the controller, otherwise we can not create and mount volumes. Could you try repairing access to api.hetzner.cloud and check if your controller then properly starts up?

**Comment by wmtbuddhika** [comment]
Hi @apricote,
Appreciate you help.

There was a problem with the DNS and I restarted the core-dns pods,
`k -n kube-system rollout restart deployment coredns
`
Now pods are able to connect to both services and pv is provisioned successfully.
I hope this conversation helps someone and I'll close the issue.

Thank you
