### ISSUE TITLE
Documentation missing for different kubelet dirs

### ISSUE THREAD

**Issue by danielr1996** [hetznercloud/csi-driver#473]
When Running a distro with a non standard kubelet dir (e.g. k0s uses `/var/lib/k0s/kubelet`) it is necessary to replace all occurences of `/var/lib/kubelet` with `/var/lib/k0s/kubelet` in the `deployment.yaml`. A hint in the `README.md` would be nice, because the errors messages are not that helpful and took me a good time to figures this out.

**Comment by apricote** [comment]
Related to #357

**Comment by apricote** [comment]
Documentation was added in https://github.com/hetznercloud/csi-driver/pull/536
