### ISSUE TITLE
The file /dev/disk/by-id/scsi-0HC_Volume_36997879 does not exist and no size was specified.

### ISSUE THREAD

**Issue by mkarg** [hetznercloud/csi-driver#504]
It seems there is a bug in the CSI driver. I am executing the [Getting Started](https://github.com/hetznercloud/csi-driver/blob/main/docs/kubernetes/README.md#getting-started), and the result of `kubectl describe pod my-csi-app` is:
```
Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Normal   Scheduled               74s               default-scheduler        Successfully assigned default/my-csi-app to kind-control-plane
  Normal   SuccessfulAttachVolume  69s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-34433eb7-96bf-4068-bd3a-205b91ae1497"
  Warning  FailedMount             4s (x8 over 68s)  kubelet                  MountVolume.SetUp failed for volume "pvc-34433eb7-96bf-4068-bd3a-205b91ae1497" : rpc error: code = Internal desc = failed to publish volume: exit status 1
mke2fs 1.46.6 (1-Feb-2023)
The file /dev/disk/by-id/scsi-0HC_Volume_36997879 does not exist and no size was specified.
```
The last line is pretty weird, because actually the file `/dev/disk/by-id/scsi-0HC_Volume_36997879` *does* exist! For testing purposes, I tried to simply manually `mount` that very same file on the node manually, and I could successfully access it from the node's OS.

I tried several times (I even recreated the k8s cluster to test it in a safe environment using `kind`), but the result is always the same.

Hence I assume this is simply a bug in the CSI driver.

(I am using k8s 1.27 with CSI driver 2.4.0)

**Comment by apricote** [comment]
Hey @mkarg,

you mentioned that you tested again with `kind`, is this also the distribution you initially used or did you use something else?

I just tested it with `kind` and can confirm that it does not work. This is because `kind` by default does not mount the `/dev/disk` directory into its environment, so the csi-driver Pod can not access it. You can confirm this by exec-ing into the kind container:

```shell
$ docker ps
$ docker exec -it kind-control-plane /bin/bash
root@kind-control-plane:/# ls /dev/disk
ls: cannot access '/dev/disk': No such file or directory
```

I was able to get it running by mounting the `/dev` directory into the kind cluster and getting rid of the other default StorageClass:

```yaml
# cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /dev
    containerPath: /dev
```

```shell
kind create cluster --config=cluster.yaml
kubectl delete sc standard
```

**Comment by mkarg** [comment]
Thank you @apricote,

in fact I am trying the Hetzner CSI driver using `kind`, and your proposed solution gets us one step nearer to the final solution: The kind-control-plane container can see all attached Hetzner volumes now in `/dev/disk/by-id`:
```
root@kind-control-plane:/# ls -la /dev/disk/by-id
total 0
drwxr-xr-x 2 root root 160 Sep 17 08:30 .
drwxr-xr-x 7 root root 140 Sep 10 12:43 ..
lrwxrwxrwx 1 root root   9 Sep 10 12:43 scsi-0HC_Volume_34837789 -> ../../sdb
lrwxrwxrwx 1 root root   9 Sep 16 22:06 scsi-0HC_Volume_36976024 -> ../../sdc
lrwxrwxrwx 1 root root   9 Sep 10 12:43 scsi-0QEMU_QEMU_HARDDISK_35217037 -> ../../sda
lrwxrwxrwx 1 root root  10 Sep 10 12:43 scsi-0QEMU_QEMU_HARDDISK_35217037-part1 -> ../../sda1
lrwxrwxrwx 1 root root  11 Sep 10 12:43 scsi-0QEMU_QEMU_HARDDISK_35217037-part14 -> ../../sda14
lrwxrwxrwx 1 root root  11 Sep 10 12:43 scsi-0QEMU_QEMU_HARDDISK_35217037-part15 -> ../../sda15
```
But unfortunately, the Hetzner volume created by the example in [Getting Started](https://github.com/hetznercloud/csi-driver/blob/main/docs/kubernetes/README.md#getting-started) is *not getting attached* to the Hetzner server running `kind`. Even after several minutes, `hcloud volume list` looks like this:
```
ID         NAME                                       SIZE    SERVER      LOCATION   AGE
34837789   volume-fsn1-1                              20 GB   hetzner-2   fsn1       57d
36976024   test                                       10 GB   hetzner-2   fsn1       2d
37048025   pvc-9239a170-e31f-49ec-a385-433293b8a129   10 GB   -           fsn1       just now
```
So it seems, the Hetzner CSI driver is *not attaching* the created volume. As a result, the POD is endlessly waiting for the new PVC:
```
Events:
  Type     Reason              Age                    From                     Message
  ----     ------              ----                   ----                     -------
  Normal   Scheduled           8m46s                  default-scheduler        Successfully assigned default/my-csi-app to kind-control-plane
  Warning  FailedMount         2m11s (x3 over 6m43s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[my-csi-volume], unattached volumes=[my-csi-volume], failed to process volumes=[]: timed out waiting for the condition
  Warning  FailedAttachVolume  22s (x12 over 8m42s)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-9239a170-e31f-49ec-a385-433293b8a129" : rpc error: code = Internal desc = failed to publish volume: volume is still in the process of being created (service_error)
```

**Comment by apricote** [comment]
Please try again. The Hetzner Cloud API had an incident yesterday that prohibited creating & attaching volumes (as well as many other things): https://status.hetzner.com/incident/06173f57-a39f-42ec-97b9-e44a818ea004

**Comment by mkarg** [comment]
Thank you, @apricote, indeed *today* it is working perfectly! 😄 

So the sole bug indeed is that nobody could know that /dev *must* be mapped into the container. So the question is: Whom to blame? Is that smething *kind* needs to say clearly in its docs, or is that specific to the Hetzner CSI driver, or is it just common sense in the k8s world? 😕 And moreover, is /dev to be mapped *only* in the controller container, or in *all* node containers of kind?

**Comment by apricote** [comment]
> Is that smething kind needs to say clearly in its docs, or is that specific to the Hetzner CSI driver, or is it just common sense in the k8s world?

This would be required for any csi-driver that wants to work with devices, including [azuredisk](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/cc27e0c93d0847c3d7214ca4e687779ebfaab2bd/pkg/azuredisk/azure_common_linux.go#L41-L45), [aws-ebs](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/838d69ffd0e1bc5b730d922d53d6b99a6df96d43/pkg/driver/node_linux.go#L123-L126) and [gcp-compute-persistent-disk](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/445215bb36105ef0b4827a879cffa2522ad1d566/pkg/deviceutils/device-utils.go#L102-L107).

Kind is the only Kubernetes distribution I have used so far that did not provide the `/dev/disk` path to its nodes. But I get why they dont do that by default (running in docker containers). Other people have already encountered the same issue: https://github.com/kubernetes-sigs/kind/issues/3069#issuecomment-1382399418

> And moreover, is /dev to be mapped only in the controller container, or in all node containers of kind?

`/dev` (perhaps its enough to mount `/dev/disk`) needs to be available on every node you want to mount a PersistentVolume on.

**Comment by mkarg** [comment]
Thank you, Julian! :-)
