### ISSUE TITLE
Volumes are attached to the http proxy

### ISSUE THREAD

**Issue by pawl1234** [hetznercloud/csi-driver#505]
Hi,
I have a openshift setup in a private networking behind a proxy. First I had trouble setting up CSI as the container hcloud-csi-driver in hcloud-csi-controller pod was constantly crashing. I tought its related to openshift security at the end it was the proxy. I guess logging should be included in such cases. After enableing debug logging I found the issue myself.

My current problem is that the volumes are created properly, but they are attached to the proxy instead of the openshift nodes. Can someone advise me how to handle this issue?

Thanks and Greetings,

**Comment by apricote** [comment]
Hey @pawl1234,

what version of the csi-driver are you using?

Could you check the `CSINode` objects and verify if the `nodeID`(Hetzner Cloud server id) in the `csi.hetzner.cloud` driver is the correct ID or the ID of the proxy server?

With current versions of csi-driver, this should be set from the metadata service, but if you proxy the requests to the metadata service on another node, it could be a wrong IP.

**Comment by pawl1234** [comment]
I'm using 2.4.0. So the Node ID is actually the ID of the Proxy Server as you described.

**Comment by pawl1234** [comment]
Hi @apricote do you have a good idea for me how to come around this proxy problem?

**Comment by pawl1234** [comment]
Ok I found a solution. I was able to add a no_proxy for the IP of the metadata service. Maybe it makes sense to bypass proxy always for metadata service, or add little documentation for how to use proxy properly. 

Thanks anyway. Greetings.
