### ISSUE TITLE
You must either provide secret.hcloudApiToken or secret.existingSecretName

### ISSUE THREAD

**Issue by MichaelVoelkel** [hetznercloud/csi-driver#518]
Hi,

not sure which details you need, but when I run:
```
KUBECONFIG=secrets/admin.conf helm install -n kube-system hcloud-csi-driver mlohr/hcloud-csi-driver --set csiDriver.secret.create=true --set csiDriver.secret.hcloudApiToken=blablabla12345
```
I get
```
Error: INSTALLATION FAILED: execution error at (hcloud-csi-driver/templates/secret.yaml:12:91): You must either provide secret.hcloudApiToken or secret.existingSecretName
```

**Comment by MichaelVoelkel** [comment]
Removing `csiDriver.` from the `--set` arguments seems to work?

**Comment by apricote** [comment]
Hey @MichaelVoelkel, you seem to be using the [Helm Chart by Matthias Lohr](https://gitlab.com/MatthiasLohr/hcloud-csi-driver-helm-chart) (`mlohr`). You can either ask them for help or use our Helm Chart instead. With our Helm Chart the option is named `controller.hcloudToken.value` or `controller.hcloudToken.existingSecret`.

**Comment by MichaelVoelkel** [comment]
ah yes. Thank you!
