### ISSUE TITLE
Plans to make the CSI working on bare metal (root) servers?

### ISSUE THREAD

**Issue by guettli** [hetznercloud/csi-driver#526]
I the [Kuberentes README of hcloud CSI](https://github.com/hetznercloud/csi-driver/blob/main/docs/kubernetes/README.md#integration-with-root-servers) I read:

> Root servers can be part of the cluster, but the CSI plugin doesn't work there. Taint the root server as follows to skip that node for the DaemonSet.

Are there plans to make the hcloud storage available on bare metal servers?

**Comment by apricote** [comment]
Hi, we don't publish roadmaps for possible upcoming features/products. But I have forwarded this to the responsible dev team so this request could go on the wishlist.
