### ISSUE TITLE
Use hetznercloud csi driver in non hetzner-cloud servers.

### ISSUE THREAD

**Issue by srkaviani** [hetznercloud/csi-driver#529]
Hi
I have a Kubernetes cluster and My nodes created in Hetzner dedicated servers. (non cloud servers)
i want to use hetzner-cloud volumes for Persistent Volume of my pods.
is there possible?

**Comment by apricote** [comment]
Duplicate of #526

Since my response to that ticket yesterday I have spoken to the responsible team and got the response that this will not be implemented in the forseeable future.
