### ISSUE TITLE
Allow passing file system formatting options (e.g. block size)

### ISSUE THREAD

**Issue by jooola** [hetznercloud/csi-driver#532]
To fine tune / optimize the file system provided by the CSI driver, we should allow users to provide a list of flags for `mkfs` to let them tweak the file system for their needs.

For example, some users request to be able to change the file system block size, and this is currently not possible using only the CSI-driver.

**Comment by jooola** [comment]
This will be fixed with the addition of fsFormatOptions in #747

**Comment by lukasmetzner** [comment]
Feature got merged in #747, so `fsFormatOptions` is available in v2.10+.
