### ISSUE TITLE
Question: can I attach a Volume to pods running on nodes that are NOT provisioned in Hetzner cloud?

### ISSUE THREAD

**Issue by copiltembel** [hetznercloud/csi-driver#569]
I have a kubernetes cluster which consists of multiple nodes. Some nodes are in the Hetzner Cloud and some are bare metal machines that are not in the Hetzner Cloud.

For the bare metal machines I need to provision some persistent storage and I am looking into Hetzner Cloud volumes through this csi-driver.

Is it possible to provision Hetzner cloud volumes to those bare metal machines outside of the Hetzner cloud?

**Comment by apricote** [comment]
Hey @copiltembel,

this is not possible. Volumes only work with Hetzner Cloud servers: https://docs.hetzner.com/cloud/volumes/faq/#can-i-also-mount-hetzner-cloud-volumes-on-a-hetzner-dedicated-root-server
