### ISSUE TITLE
registry.k8s.io 403, blacklisted ip

### ISSUE THREAD

**Issue by ZhouJian26** [hetznercloud/csi-driver#592]
### TL;DR

Some hetzner ip are blacklisted by registry.k8s.io

### Expected behavior

Be able to use the images from registry.k8s.io from any hetzner ip

### Observed behavior

got 403 when the kubernetes cluster try to pull the csi images

### Log output

```plain text
Failed to pull image "registry.k8s.io/sig-storage/livenessprobe:v2.9.0": failed to pull and unpack image "registry.k8s.io/s │
│ ig-storage/livenessprobe:v2.9.0": failed to resolve reference "registry.k8s.io/sig-storage/livenessprobe:v2.9.0": unexpected status from HEAD request to https://registry.k8s.io/v2/s │
│ ig-storage/livenessprobe/manifests/v2.9.0: 403 Forbidden
```
```


### Additional information

_No response_

**Comment by jooola** [comment]
@ZhouJian26 Could you please open a ticket via the support channel https://console.hetzner.cloud/support so we can investigate your issue?

Closing the ticket as it is not directly related to the csi-driver.

**Comment by rbjorklin** [comment]
I have successfully worked around this by using [peerd](https://github.com/Azure/peerd) ( you may also want to try [spegel](https://github.com/spegel-org/spegel)).
