### ISSUE TITLE
Running csi-driver on Hetzner bare-metal machines

### ISSUE THREAD

**Issue by dderkach-dedicatted** [hetznercloud/csi-driver#597]
### TL;DR

Hello, I am following a manual for kubernetes installation. My k8s cluster is consists of 3 bare metal Hetzner machines.
On hcloud-csi-node pod, I see an error: _"msg="unable to connect to metadata service, are you sure this is running on a Hetzner Cloud server?"_
Is your driver only for clusters into Hetzner Cloud, not for Hetzner bare metal? 

### Expected behavior

Maybe you can suggest what driver I can use to create a persistent volumes for Prometheus on Hetzner Bare Metal machines?
Thanks in advance!

**Comment by apricote** [comment]
This csi-driver is only able to create & mount volumes in Hetzner Cloud to Hetzner Cloud servers. It is not possible to use these volumes with Hetzner Dedicated/Robot servers: https://docs.hetzner.com/cloud/volumes/faq/#can-i-also-mount-hetzner-cloud-volumes-on-a-hetzner-dedicated-root-server

Depending on your needs, you could use the local disks directly ([`local` PersistentVolumes](https://kubernetes.io/docs/concepts/storage/volumes/#local), `hostPath`) or layer some distributed block storage solution on top for redundancy ([Longhorn](https://longhorn.io/), Ceph, OpenEBS,. ..). We have no official recommendation and do not provide support for any of these.
