### ISSUE TITLE
Export Prometheus metrics

### ISSUE THREAD

**Issue by thcyron** [hetznercloud/csi-driver#60]
At least we should export some Go runtime metrics, probably also number of API calls per endpoint and error rates.

**Comment by apricote** [comment]
I started working on this feature. You can find the progress in my fork on branch [`feature/prometheus`](https://github.com/apricote/csi-driver/tree/feature/prometheus).

To gather the gRPC metrics, I used the [go-grpc-prometheus](https://github.com/grpc-ecosystem/go-grpc-prometheus) library

I will create a PR once this is a bit more polished.

**Comment by LKaemmerling** [comment]
Implemented with #67
