### ISSUE TITLE
Server identification via hc-utils

### ISSUE THREAD

**Issue by ahedderich** [hetznercloud/csi-driver#64]
I was setting up a cluster in a virtual network. A gateway server would provide internet access for the cluster nodes. Everthing worked fine but when creating a pv the volume is attached the gateway server instead of the cluster node.

So far i didn't have time to find in the code how the server to attach to is identified but i would guess from that behavior it's identified by the main ip address.
Since the cluster nodes in my case don't use the eth0 device, it doens't work anymore.

Would it be possible to use a unique identifer in the config of hc-utils to securly identify the correct server to attach to?

**Comment by LKaemmerling** [comment]
At the moment it is not possible to use another method than calling the metadata service (which lives on 169.254.169.254). You should enable the public interface and add a specific route for this IP and route all other traffic through the gateway server.
