### ISSUE TITLE
How do you Backup?

### ISSUE THREAD

**Issue by theWeird** [hetznercloud/csi-driver#79]
Since hetzner cloud volumes cannot be included in snapshots or automatic backups, data on volumes have to be backed up by some other process, e.g. borg on storage boxes.

How do you achieve that?

I see that the new created volume is mounted at paths like:
```
/dev/disk/by-id/scsi-0HC_Volume_3701950 ext4        9.8G   37M  9.8G   1% /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4dc85a0b-6856-48c7-8efa-079a5dbe095b/globalmount
/dev/disk/by-id/scsi-0HC_Volume_3701950 ext4        9.8G   37M  9.8G   1% /var/lib/kubelet/pods/6b58575d-433d-4de7-bfae-9c2f432e4e73/volumes/kubernetes.io~csi/pvc-4dc85a0b-6856-48c7-8efa-079a5dbe095b/mount
```

So do you just include `/var/lib/kubelet/plugins/kubernetes.io/csi/pv` in your backup?  
Or do you have any backup strategy to have the backup data organized by volume names instead of IDs?

**Comment by codeagencybe** [comment]
I'm interested to know too. 
I would like the backups to automatically store on WASABI (S3 compatible endpoint) which is lots cheaper, faster and solid than Amazon S3. 
One simple price tier as 6$ per month for 1TB included. No cost for ingress, egress, calls, connections etc... 

On the other hand, I'm looking into Rook and OpenEBS. I have just recently purchase a subscription for MayaDirector (for OpenEBS) to have CAS (container attached storage) so basically I have less to worry about the storage itself. It replicates itself around the cluster but still figuring out as much as possible and working with one of the OpenEBS engineers.

**Comment by theWeird** [comment]
The intention of my question was to find out about some solutions to backup the created volumes with some selfwritten scripts ;)

If there was an automation for backups in this CSI driver, I'd prefer backups using borg on hetzners storage boxes for the first run. In my cluster run applications with sensitive data, so storages on servers of a non-EU company are an absolute show-stopper for backup ;)  
And btw. in my opinion this driver is about utilizing Hetzner infrastructure in kubernetes clusters ;)

**Comment by codeagencybe** [comment]
Oh ok, sorry for the mis-interpretation. 
Well, you can also have a look at MinIO, it's a self hosted S3 bucket platform and often used in K8s. 
https://min.io/

I'm currently working myself through a solution with the help from OpenEBS. I purchased their MayaOnline (Director) plan and it comes with personal support plan to help the launch on K8s. 
And their engineer also came with this suggestion to use MinIO. 
Happy to share my experience and insights as soon as I got further with the install today/tomorrow. 

Btw, WASABI has also storage locations in Europe ;) 
So in terms of GDPR, everything is good.

**Comment by koehn** [comment]
I've been using velero, which in turn uses restic to back up k8s volumes to S3-compatible storage e.g., wasabi. It works really well.

**Comment by LKaemmerling** [comment]
I will close this issue, as this is not a problem directly related to the CSI Driver (or at least a problem with the CSI Driver itself). Of course, you can discuss in this issue about your Backup Solutions.

**Comment by 205g0** [comment]
Chiming in here, hoping that some new options to backup Hetzner volumes have arisen but I guess not. If you have any new ideas please let us know!

**Comment by ArgonQQ** [comment]
Is there something planned in the near future @LKaemmerling ? Would highly appreciate this.

**Comment by fnkr** [comment]
Once https://github.com/hetznercloud/csi-driver/pull/200 is merged, btrfs snapshots might be a good solution.
