### ISSUE TITLE
Resize fails with missing executable?

### ISSUE THREAD

**Issue by drallgood** [hetznercloud/csi-driver#86]
`215 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/csi.hetzner.cloud^3590545\"" failed. No retries permitted until 2019-12-11 21:54:24.201873888 +0100 CET m=+92254.142515252 (durationBeforeRetry 2m2s). Error: "NodeExpandVolume.NodeExpandVolume failed for volume \"pvc-8cdc0c30-548e-4cdb-babb-fd04f2a6cd0d\" (UniqueName: \"kubernetes.io/csi/csi.hetzner.cloud^3590545\") pod \"docker-registry-776c9d6d75-mrjp6\" (UID: \"d1c497c2-7ec3-4585-aca6-3f6c5cfda099\") : MountVolume.NodeExpandVolume failed : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = failed to resize volume: resize of device /dev/disk/by-id/scsi-0HC_Volume_3590545 failed: executable file not found in $PATH. resize2fs output: "
`

The executable is available on the host. Any ideas?

**Comment by ezlo-eugenek** [comment]
Faced with same issue, problem is that resize2fs is not installed in hcloud-csi-driver image. As quick fix you can do:

for pod in `kubectl get pod -l app=hcloud-csi -n kube-system --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}'`;do kubectl exec -n kube-system -it $pod -c hcloud-csi-driver -- apk add e2fsprogs-extra;done
 
And remove dangling pod.

### In loop about kube-system namespace is used, which is default for this csi driver, if you use other ns, pls change it accordingly.

**Comment by drallgood** [comment]
That makes a lot of sense. I was checking all other places but never thought about the `hcloud-csi` pods
