### ISSUE TITLE
Volume snapshots

### ISSUE THREAD

**Issue by acim** [hetznercloud/csi-driver#88]
Do you plan to support volume snapshots soon?

**Comment by thelittlebug** [comment]
how would you implement a snapshot feature hetzner didn't provide? do you have any plans?

**Comment by acim** [comment]
https://github.com/kubernetes-csi/external-snapshotter/

**Comment by LKaemmerling** [comment]
We know that there is a high demand for adding snapshot support to our volumes.  We already have this on our whishes list but can not tell you if or when we will add snapshots to volumes. We announce new features mostly on our Twitter Account: https://twitter.com/Hetzner_Online 

If we add snapshots to our volumes, we will add them, of course, to the CSI driver too.

**Comment by tomazb** [comment]
And after 15 months still no snapshot support for the attached volumes?

**Comment by dprandzioch** [comment]
I also couldn't find anything in the documentation - just to clarify: Is this feature implemented by now or is it still not possible to create snapshots of PVs?

**Comment by Lars147** [comment]
> I also couldn't find anything in the documentation - just to clarify: Is this feature implemented by now or is it still not possible to create snapshots of PVs?

As of today, the Hetzner Cloud documentation states that no snapshot or backup functionality is provided for volumes.

![image](https://user-images.githubusercontent.com/48560605/124731710-c3a97480-df12-11eb-8d55-702ccdecd27f.png)

**Comment by FloMaetschke** [comment]
Nearly 2 years ago, still no snapshot support for hcloud volumes.

**Comment by thelittlebug** [comment]
maybe its a feature? :D

**Comment by kj89** [comment]
I would love if this feature existed. But looks like its not in their priority or there is some other reasons why they dont implement such a high demand feature

**Comment by fhofherr** [comment]
Hi,

this is a feature that needs to be implemented in the Hetzner Cloud Backend first. As such this not the right place for this feature request.  I'm therefore closing this thread.
