### ISSUE TITLE
Multi-Attach error for volume 

### ISSUE THREAD

**Issue by wacken89** [hetznercloud/csi-driver#89]
Hello,
Problems appears when shutdown server with mounted volumes.  

<img width="538" alt="Screenshot 2019-12-31 13 42 31" src="https://user-images.githubusercontent.com/23267713/71620633-89e80700-2bd3-11ea-8895-e231085e467f.png">

```sh 
kubectl get nodes
k8s-worker-main-01-dc3-nbg1    NotReady   <none>   82d    v1.16.3
```

When i delete pod with volume, new pod couldn't start 
```
Events:
  Type     Reason              Age        From                     Message
  ----     ------              ----       ----                     -------
  Normal   Scheduled           <unknown>  default-scheduler        Successfully assigned sonar/sonar-postgresql-0 to k8s-worker-main-02-dc3-nbg1
  Warning  FailedAttachVolume  5s         attachdetach-controller  Multi-Attach error for volume "pvc-b9190e94-39ee-42cb-af3b-d4b5d9cb81b1" Volume is already exclusively attached to one node and can't be attached to another
```

Problem with pod could be solved by deleting `volumeattachments`

```sh
kubectl delete volumeattachments.storage.k8s.io csi-2c19fb72414d1ea43868868fa47e73a7adecbd04ca707fb4731cefcd60efe379
```

After that volume could be attached to new server and pod started

## Expectation

Volume will be detached and attached automatically

**Comment by ninja-** [comment]
yeah these volume mount locks take an awful amount of time to timeout. 
Thanks for the workaround though :)
But I've had similar problems even on GKE where the locks can be a pain too...

**Comment by aspettl** [comment]
I hope that this problem could be solved using an approach like e.g. https://github.com/kubernetes/enhancements/pull/1116 (i.e., it needs changes in Kubernetes itself).
I guess at the moment there is no way to do it in the csi driver.
