### ISSUE TITLE
Consider allowing overriding names of PV's

### ISSUE THREAD

**Issue by aaahrens** [hetznercloud/csi-driver#90]
From a disaster recovery perspective it would be *really* nice to be able to name important volumes with the uuid after it i.e. client-1-postgres-uuidstring. That way in case of a cluster being destroyed we know what to re-import without having to mount and find data. 

Since there already exist tooling to backup volumes within hetzner (and without the need for s3 compatible services), it would make scaffolding/duplication a hell of a lot easier as well.

**Comment by bascht** [comment]
We're currently using the Volume labels as a bit of a stop gap. You can use the Hetzner API to set and read the labels. Not ideal, but at least it spares us the need to mount and manually check them. :D

**Comment by spatialy** [comment]
hi @bascht, can you share you work around this with labels and API?

**Comment by bascht** [comment]
@spatialy Oh – it's really just using the `hcloud` CLI and setting the labels accordingly.

So – `kubectl get pvc / pv` and set the labels of the volumes via `hcloud volume list / add-label …`
For the really important stuff I also like to use `hcloud volume enable-protection …` so it doesn't get lost in a hurry. I rather deal with a wonky finaliser than lost data. :D

**Comment by nejtr0n** [comment]
Any ideas how to override gerated volume name by driver?

**Comment by malikkirchner** [comment]
Prefix-naming or labeling volumes from the k8s volume claim would be useful. Is there any work planned to implement this?
