### ISSUE TITLE
failed to expand volume: size downgrade is not allowed

### ISSUE THREAD

**Issue by hmettendorf** [hetznercloud/csi-driver#91]
Hi guys,

I'm experiencing an issue with the version 1.2.2. After manually editing a pvc and increasing the requested storage size from 10Gi to 25Gi the resizer responses with an error:

`
I0104 12:57:30.610556       1 controller.go:224] Started PVC processing "cluster-services/chartmuseum-chartmuseum"

I0104 12:57:30.624836       1 connection.go:180] GRPC call: /csi.v1.Controller/ControllerExpandVolume

I0104 12:57:30.624866       1 connection.go:181] GRPC request: {"capacity_range":{"required_bytes":26843545600},"volume_id":"3919711"}

I0104 12:57:30.626826       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"cluster-services", Name:"chartmuseum-chartmuseum", UID:"2fd63c9e-9f5c-4ed6-8773-54e96d8a3ed2", APIVersion:"v1", ResourceVersion:"184502", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-2fd63c9e-9f5c-4ed6-8773-54e96d8a3ed2

I0104 12:57:30.783900       1 connection.go:183] GRPC response: {}

I0104 12:57:30.784463       1 connection.go:184] GRPC error: rpc error: code = Internal desc = failed to expand volume: size downgrade is not allowed (invalid_input)

E0104 12:57:30.784477       1 controller.go:360] Resize volume "pvc-2fd63c9e-9f5c-4ed6-8773-54e96d8a3ed2" by resizer "csi.hetzner.cloud" failed: rpc error: code = Internal desc = failed to expand volume: size downgrade is not allowed (invalid_input)
`
The actual volume in the Hetzner cloud has been resized to 25Gi, but the pvc in kubernetes stays at 10Gi.

Is there a way I can fix this?

Thanks!

**Comment by LKaemmerling** [comment]
Could you please try to change it to 26Gi ? After that you need to restart the pod where the volume is attached, after the pod is restarted the PVC should have the correct size. (26 Gi)
